### ISSUE TITLE
File seems to loop endlessly in ArgumentExpander

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#1022]
The attached file, when run by ExtractCdrMetaFormDirectory, seems to loop endlessly in the ArgumentExpander until there is an out of memory error.  I'm trying to run it in a simpler program, but haven't gotten it to work.  The problematic sentence seems to be
```
15.0 20.0 25.0 30.0 35.0 40.0 45.0 Ja n -1 7 A p r1 7 Ju l1 7 O ct -1 7 Ja n -1 8 A p r1 8 Ju l1 8 O ct -1 8 Ja n -1 9 A p r1 9 Ju l1 9 O ct -1 9 Ja n -2 0 A p r2 0 Ju l2 0 Price trend of teffin Addis Ababa market Teff' white Teff' mixed Maize prices reduced or remained stable since June through August in most markets following harvests in unimodal areas but also increased imports from Uganda and Tanzania after the Government issued permits for private companies to import about 4 million bags of maize.
```
The filename needs to have .txt removed to be used with the program.

[630a3467d24e80c8e6097f2971794b82.json.txt](https://github.com/clulab/eidos/files/6551202/630a3467d24e80c8e6097f2971794b82.json.txt)

**Comment by kwalcock** [comment]
This one seems to loop forever in the SRLCompositionalGrounder.  The sentence is 

```
BOOST INCOME TO SUPPORT FOOD SECURITY AND NUTRITION .
```
from the attached file.  It does seem to loop in ExtractFromText.

[1e533493057c91173ac82bf821f7f82c.json.txt](https://github.com/clulab/eidos/files/6581565/1e533493057c91173ac82bf821f7f82c.json.txt)

**Comment by BeckySharp** [comment]
until I can get something to run, I can't debug this :(

**Comment by kwalcock** [comment]
Something is wrong, but I'm fairly sure you aren't *doing* anything wrong.  Recent updates have worked on Windows, Docker, and several Linux machines.  I'm going to try a Mac.

**Comment by kwalcock** [comment]
Unfortunately the Mac I have access to has some networking issues and can't communicate with Artifactory right now.  This will probably need to wait a little while until it gets sorted out.

**Comment by BeckySharp** [comment]
ok, well in the meantime I can't use Eidos apparently

**Comment by kwalcock** [comment]
Does `git status` or `git fsck` turn up anything useful?  Is it a relatively new clone of eidos and it isn't a zipped version without the .git directory, right?  It seemed like the sbt-git extension was having problems.

**Comment by BeckySharp** [comment]
git status looks normal, here is the other

(nsf) bsharp@Beckys-MacBook-Pro ~/github/eidos (master)]$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (56881/56881), done.
dangling commit c5122ab9d12b96d367a3b2bf14f0f8a532dc7a6b
dangling blob f2dd49d0413c02529d8403981259fae5f17e6c4e

**Comment by BeckySharp** [comment]
You know, I went ahead and recloned it and now it seems to be working....?
maybe there was some weird artifact that was confusing things?

**Comment by BeckySharp** [comment]
ok, @kwalcock ,  so the second example is fixed with #1033 
The first, though, is different. 
It's very hard to debug bc of the length, and I was thinking that it may be the case that we should handle sentences like this by removing them in the beginning.  At one time there was a check for overly long sentences, and they were excluded or skipped, but I can't seem to find it now.
Is it one of the refiners and I am blind? Or did it get removed?
If it's still there, can you please give a pointer and I'll add something for this too, likely based on the number of numbers or something (to basically scan for misparsed tables)

**Comment by kwalcock** [comment]
I think it's what this cutoff is for:
```scala
object EidosProcessor extends Logging {

  def apply(language: String, cutoff: Int = 200): EidosProcessor = language match {
```

**Comment by BeckySharp** [comment]
thanks!!
