### ISSUE TITLE
Eidos can't reground with SRLCompositionalGrounder

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#1025]
The JLDSerializer serializes `GraphMap.UNIVERSAL_ENHANCED` dependencies.  The SRLCompositionalGrounder seems to use `GraphMap.ENHANCED_SEMANTIC_ROLES` via sentence.enhancedSemanticRoles.  That's just not going to work.  Exceptions are thrown when performing the grounding on documents reread from jsonld.  I think that we will have to reread them.  Does @BeckySharp see it that way as well?

**Comment by BeckySharp** [comment]
weren’t they saved/serialized with the document when you last read them?
they were parsed with the fastnlpprocessorwithsemanticroles right? i think
that EnglishEidosProcessor extends that and the PR to processors recently
added the enhanced.

**Comment by BeckySharp** [comment]
i’ll look as soon as i’m home, we’ll fix it no matter what

**Comment by kwalcock** [comment]
P.S. The documents were last read on Wednesday.

**Comment by BeckySharp** [comment]
@kwalcock you're right about the serialization, we don't have the info anymore, sorry I thought the doc was serialized as is.
It think it will be ok though, we can re-annotate when we reground. It will be slower for sure, but less slow than re-annotating the whole corpus and everything. Let me see what needs to change in the SRLGrounder

**Comment by BeckySharp** [comment]
@kwalcock what entrypoint are you using for regrounding?

**Comment by BeckySharp** [comment]
ok @kwalcock I pushed a hotfix on the `grounder_hotfix` branch, can you see if that resolves the issue with regrounding?
If not, we can re-read but this should be faster I think.

**Comment by kwalcock** [comment]
It's in a branch that I will track down.  Are you saying that just a part of processors can be rerun?  I guess so.  The first reading took about 20 hours on two machines.  The tradeoff is not clear yet.

**Comment by BeckySharp** [comment]
if we use this hotfix, we will reparse the sentences with causal extractions.  the downside is that we will reparse them twice (once for cause and once for effect), the upside is we _won't_ reparse all sentences, and I think it's a pretty small subset of the sentences that have causal relations.  that said, i def didn't profile it :D

**Comment by kwalcock** [comment]
I see the branch, but it might need a push.  git has been acting up for me, so I'm not sure.

**Comment by BeckySharp** [comment]
> I see the branch, but it might need a push. git has been acting up for me, so I'm not sure.

no that was my bad, sorry! look now

**Comment by kwalcock** [comment]
There was enough time to run them all again, so I did that.  It's probably a good idea to keep the change, perhaps including a warning message.  Maybe eidos can save both kinds of graphs, or favor the kind that is most needed.  It didn't seem like a good time to hurry the change through.

**Comment by kwalcock** [comment]
The other graphs have been serialized now, so regrounding should be possible.
