### ISSUE TITLE
is this still used anywhere?

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#1057]
https://github.com/clulab/eidos/blob/9f3c007da0096726ccb5bc5457a9fb4c93c13d40/src/main/resources/reference.conf#L16

AFAIK the on/off of the lexicons is specified in the finders list (i.e., by including/excluding `gazetteer`).

**Comment by kwalcock** [comment]
It doesn't seem to be.  It is being handled in #1066.
