### ISSUE TITLE
EIDOS, or Eidos, what is in a name

### ISSUE THREAD

**Issue by kingfish777** [clulab/eidos#1136]
Greetings,
I am in the midst of the final edits before submitting an article for publication. I have a question to ask you: what is the original and meaning of the name "Eidos," and what is the preferred capitalization pattern? Does EIDOS stand for anything (extraction, information, Greek eidos meaning shape or form, etc.) Any further info would be helpful. Thanks! Scott

**Comment by BeckySharp** [comment]
@kingfish777 it doesn't stand for anything, much in contrast with the great DARPA tradition of _everything_ being an acronym. We did, however, select the name for its greek reference to forms/ideas, etc.  I think most of us capitalize it like `Eidos` but no hard feelings either way :)

fun question, thanks for asking!

@MihaiSurdeanu hope it's ok I answered this one :)

**Comment by BeckySharp** [comment]
oh, also, there's a citation for it -- 
```
@inproceedings{sharp2019eidos,
  title={Eidos, INDRA, \& Delphi: From free text to executable causal models},
  author={Sharp, Rebecca and Pyarelal, Adarsh and Gyori, Benjamin and Alcock, Keith and Laparra, Egoitz and Valenzuela-Esc{\'a}rcega, Marco A and Nagesh, Ajay and Yadav, Vikas and Bachman, John and Tang, Zheng and others},
  booktitle={Proceedings of the 2019 Conference of the North American Chapter of the Association for Computational Linguistics (Demonstrations)},
  year={2019}
}
```
if that helps!

**Comment by kwalcock** [comment]
![image](https://user-images.githubusercontent.com/8679738/179916201-8357b95f-8d05-47a2-89bb-93f95897ae54.png)
