### ISSUE TITLE
Affect relation -- X was affected by Y

### ISSUE THREAD

**Issue by ajaynagesh** [clulab/eidos#135]
per convo between Ajay and Becky:
When X and Y share semantic polarity (i.e., rainfall and crop production), implied increase 
When X and Y don't (i.e., rainfall deficit and crop production), implied decrease...
simple EdgeSpec(Y, Causal, X) doesn't capture this, but without Affect relation that is the best fit?

**Comment by BeckySharp** [comment]
this will be addressed in different way upcoming
