### ISSUE TITLE
JSON serialization has multiple instances of same event

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#147]
For the sentence
```
The government promotes improved cultivar to boost agricultural production for ensuring food security.
```
The JSON output contains 4 copies of the same event, here with ID E:-1154077341:
```
    {
      "type": "EventMention",
      "id": "E:-1154077341",
      "text": "cultivar to boost agricultural production",
      "labels": [
        "Causal",
...

```
with the same foundBy, same arguments that have the same IDs, etc. Note that this is the JSON I obtain from `serialization.json.WMJSONSerializer`.

Is this a serialization issue or something else?

**Comment by bgyori** [comment]
I noticed that I ran into this in a somewhat older version of Eidos, I'm testing with the latest to see if the issue persists.

**Comment by bgyori** [comment]
Yes, issue persists with latest version.

**Comment by kwalcock** [comment]
I was recently writing some serialization tests and it would not be
inconvenient for me to add this to the suite and try to see what is
happening.  If nobody objects, I'll proceed.

**Comment by kwalcock** [comment]
FWIW there are actually two pairs with slightly different foundBy values

"foundBy" : "simple-np++Increase_ported_syntax_6_verb++Increase_ported_syntax_1_verb",
"foundBy" : "simple-np++Increase_ported_syntax_6_verb++Increase_syntax_1_verb_edited",

foundBy must not be used in calculating the id, and maybe that's a problem.  Why are there pairs, though?

**Comment by MihaiSurdeanu** [comment]
Oh. Increase_ported_syntax_1_verb and Increase_syntax_1_verb_edited found the same event. We should remove duplicates, even when found by different rules.

**Comment by kwalcock** [comment]
It doesn't appear to be the serialization.  The output seems to match the input that it gets.

**Comment by kwalcock** [comment]
Here's the output from EidosShell for the sentence.  How many are considered duplicates?

entities:
List(NounPhrase, Entity) => government
	------------------------------
	Rule => simple-np
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => government
	------------------------------

List(NounPhrase, Entity) => cultivar
	------------------------------
	Rule => simple-np++Increase_ported_syntax_6_verb++Increase_ported_syntax_1_verb
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => cultivar
	  * Attachments: Increase(improved,None), Increase(promotes,None)
	------------------------------

List(NounPhrase, Entity) => cultivar
	------------------------------
	Rule => simple-np++Increase_ported_syntax_6_verb++Increase_syntax_1_verb_edited
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => cultivar
	  * Attachments: Increase(improved,None), Increase(boost,None)
	------------------------------

List(NounPhrase, Entity) => agricultural production
	------------------------------
	Rule => simple-np++Increase_ported_syntax_1_verb
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => agricultural production
	  * Attachments: Increase(promotes,None)
	------------------------------

List(NounPhrase, Entity) => agricultural production
	------------------------------
	Rule => simple-np++Increase_ported_syntax_1_verb
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => agricultural production
	  * Attachments: Increase(boost,None)
	------------------------------

List(NounPhrase, Entity) => food security
	------------------------------
	Rule => simple-np
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => food security
	------------------------------


events:
List(Causal, DirectedRelation, EntityLinker, Event) => government promotes improved cultivar
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => promotes
	cause (NounPhrase, Entity) => government
	effect (NounPhrase, Entity) => cultivar
	  * Attachments: Increase(improved,None), Increase(promotes,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => government promotes improved cultivar
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => promotes
	cause (NounPhrase, Entity) => government
	effect (NounPhrase, Entity) => cultivar
	  * Attachments: Increase(improved,None), Increase(boost,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => government promotes improved cultivar to boost agricultural production
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => promotes
	cause (NounPhrase, Entity) => government
	effect (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(promotes,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => government promotes improved cultivar to boost agricultural production
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => promotes
	cause (NounPhrase, Entity) => government
	effect (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(boost,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => cultivar to boost agricultural production
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => boost
	cause (NounPhrase, Entity) => cultivar
	  * Attachments: Increase(improved,None), Increase(promotes,None)
	effect (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(promotes,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => cultivar to boost agricultural production
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => boost
	cause (NounPhrase, Entity) => cultivar
	  * Attachments: Increase(improved,None), Increase(promotes,None)
	effect (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(boost,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => cultivar to boost agricultural production
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => boost
	cause (NounPhrase, Entity) => cultivar
	  * Attachments: Increase(improved,None), Increase(boost,None)
	effect (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(promotes,None)
	------------------------------

List(Causal, DirectedRelation, EntityLinker, Event) => cultivar to boost agricultural production
	------------------------------
	Rule => ported_syntax_1_verb-Causal
	Type => EventMention
	------------------------------
	trigger => boost
	cause (NounPhrase, Entity) => cultivar
	  * Attachments: Increase(improved,None), Increase(boost,None)
	effect (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(boost,None)
	------------------------------

List(Origin, DirectedRelation, EntityLinker, Event) => agricultural production for ensuring food security
	------------------------------
	Rule => origin-2
	Type => EventMention
	------------------------------
	trigger => for
	origin (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(promotes,None)
	theme (NounPhrase, Entity) => food security
	------------------------------

List(Origin, DirectedRelation, EntityLinker, Event) => agricultural production for ensuring food security
	------------------------------
	Rule => origin-2
	Type => EventMention
	------------------------------
	trigger => for
	origin (NounPhrase, Entity) => agricultural production
	  * Attachments: Increase(boost,None)
	theme (NounPhrase, Entity) => food security
	------------------------------

**Comment by kwalcock** [comment]
Here are the IDs and the foundBy values.  For the quadruple E:-1154077341, it is the apparently normal duplication from promotes/boost plus another duplication due to the two different foundBy values for T:1232771938.  This doesn't seem to be a serialization issue.

Vector(
(T:1282900093,simple-np), 

(T:385191655,simple-np++Increase_ported_syntax_1_verb), 
(T:385191655,simple-np++Increase_ported_syntax_1_verb), 

(T:-1504839551,simple-np), 

(T:1232771938,simple-np++Increase_ported_syntax_6_verb++Increase_ported_syntax_1_verb), 
(T:1232771938,simple-np++Increase_ported_syntax_6_verb++Increase_syntax_1_verb_edited), 

(E:-1154077341,ported_syntax_1_verb-Causal), 
(E:-1154077341,ported_syntax_1_verb-Causal), 
(E:-1154077341,ported_syntax_1_verb-Causal), 
(E:-1154077341,ported_syntax_1_verb-Causal), 

(E:-564057589,ported_syntax_1_verb-Causal), 
(E:-564057589,ported_syntax_1_verb-Causal), 

(E:-1729593658,origin-2), 
(E:-1729593658,origin-2), 

(E:611062274,ported_syntax_1_verb-Causal), 
(E:611062274,ported_syntax_1_verb-Causal))

**Comment by bsharpataz** [comment]
We thought we were removing duplicates by type, apparently it still needs
work.  BUT if we move to hyper edges BEFORE addressing this, then the
simple solution of keeplongest (as is done in REACH) will work I think...?

**Comment by kwalcock** [comment]
Thanks, Becky!  I was about to ask if I need to make some kind of filter.  For the moment it might be better if I just make a test case for duplicates and mark it as a failing test.  It can be revisited after some of the changes you mention.

**Comment by bsharpataz** [comment]
ok -- so to add hyper edges for real-real we need to:
- add the hyper edge-ness to the entityLinker rules at least
- add hyper-edges to the testing framework (if they're not there already)
- modify all test files to use hyper edges (old and current)

knowing the priority list, @MihaiSurdeanu would you rather we do hyper edges first and then address this duplication bug with the straightforward keepLongest? or should we fix duplication bug and move to hyper edges later?

For reference, this method (https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/EidosActions.scala#L67) is intended to fix duplication.  it may be as simple as modifying it to add a .head() and removing the trigger from the grouping.... I'll try now...

**Comment by MihaiSurdeanu** [comment]
- I don't understand what hyper edges have to do with this...
- I think it's a clear duplication issue: two different rules produce the same entity "agricultural production". Why can't we remove it with keepLongest now?

**Comment by MihaiSurdeanu** [comment]
- In any case, I think we should wait on the hyper edges until the other parts are in place for Monday.

**Comment by bsharpataz** [comment]
I fixed it easier than I thought.  The keepLongest doesn’t work without
hyper edges bc if A and B cause C, then B cause C will always get lost bc
of the longer span of A cause C.
But moot, Bc it’s  fixed
