### ISSUE TITLE
Getting grounding in JSON-LD output

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#185]
We're working on processing grounding information from the JSON-LD output (can get it from the example json-ld file posted here on Github) but haven't yet figured out how to run the reader and the serializer to get the groundings in the output. We found that running the example at https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/apps/examples/ExtractFromText.scala
doesn't produce the grounding entries for each of the entities. What would need to be changed to get those?

**Comment by MihaiSurdeanu** [comment]
Clearly this is a bug, @bsharpataz?

**Comment by bsharpataz** [comment]
@MihaiSurdeanu and @bgyori Try changing https://github.com/clulab/eidos/blob/master/src/main/resources/eidos.conf#L14 to `true` -- and you'll have to change the path to point to your local copy of the w2v vectors.
I think it will run then.  We have it `false` by default in github bc the vectors are quite large

**Comment by bsharpataz** [comment]
@bgyori please let me know if that doesn't fix it

**Comment by bgyori** [comment]
I see, that makes sense, but vectors.txt isn't in version control as far as I see. Do you plan to make it publicly available in some other way?

**Comment by MihaiSurdeanu** [comment]
It's in the Drive, under resources/

**Comment by bsharpataz** [comment]
ah, you beat me to it! well here's the link https://drive.google.com/drive/u/1/folders/1R1oEuHC3yyXAW2NGf2ohpUKUNcExQ6cv

**Comment by bgyori** [comment]
Thanks @djmilstein will try to make it work and report back. Please grant him access to the drive, thanks!

**Comment by ajaynagesh** [comment]
Shared the vectors.txt with @djmilstein

**Comment by djmilstein** [comment]
Thank you everyone, I got the file and making progress! I put the file in src/main/resources/org/clulab/wm/eidos/w2v/vectors.txt. In src/main/resources/eidos.conf, I set:
```
wordToVecPath = "/org/clulab/wm/eidos/w2v/vectors.txt"
useW2V = true
```

I then rebuild the jar file with:
```sbt compile
sbt assembly``

With the newly built jar in my CLASSPATH, I ran the ExtractFromText example. The good news is that it looks like it found vectors.txt since it outputs:
```wordToVecPath: /org/clulab/wm/eidos/w2v/vectors.txt
domainOntoPath: /org/clulab/wm/eidos/toy_ontology.yml
Sourcing resource: file:/Users/daniel/software/eidos/target/scala-2.12/eidos-assembly-0.1.6-SNAPSHOT.jar!/org/clulab/wm/eidos/toy_ontology.yml
Sourcing resource: file:/Users/daniel/software/eidos/target/scala-2.12/eidos-assembly-0.1.6-SNAPSHOT.jar!/org/clulab/wm/eidos/w2v/vectors.txt
14:45:07.351 [main] DEBUG o.c.embeddings.word2vec.Word2Vec - Started to load word2vec matrix from source ...
14:46:05.265 [main] DEBUG o.c.embeddings.word2vec.Word2Vec - Completed matrix loading.
14:46:06.099 [main] DEBUG o.c.embeddings.word2vec.Word2Vec - Completed matrix loading.
```

However, alas! There still is no grounding information in the JSON-LD output. Happy to try further steps or supply more information.

**Comment by kwalcock** [comment]
FWIW I'll give it a try.

**Comment by kwalcock** [comment]
This will be checked-in momentarily, but it takes 15 minutes to process.  Change

import org.clulab.wm.eidos.serialization.json.odin.JLDCorpus

to

import org.clulab.wm.eidos.serialization.json.JLDCorpus

without the odin.

**Comment by kwalcock** [comment]
The one-line fix is available via GitHub now.  There should be some documentation on the download and settings for the vector file in the relatively near future.

**Comment by djmilstein** [comment]
It works now! Thank you, everybody!
