### ISSUE TITLE
How to get JSON-LD with groundings?

### ISSUE THREAD

**Issue by adarshp** [clulab/eidos#212]
What is the invocation for getting a JSON-LD file with Eidos mentions with attached groundings? I tried doing 

sbt “runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../../ml4ai/WorldModelers/MITRE_Evaluation_Documents output_dir”

but the output .jsonld files do not have the grounding information.

**Comment by kwalcock** [comment]
This may not be enough, but see the section "Related resources" towards the bottom of readme.md to begin.

**Comment by bsharpataz** [comment]
Is the word2vec loading?

**Comment by adarshp** [comment]
Ok, got it - I am downloading the 2.3G vector file and will try it with useW2V=true. I'll let you know if it works.

**Comment by kwalcock** [comment]
I think it worked, so closing now.

**Comment by adarshp** [comment]
Sorry, forgot to update - yes it worked!
