### ISSUE TITLE
copular quants

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#214]
[resolved for this issue]
"We are now seeing sharp spikes of need in new areas, such as Eastern Equatoria or Western
Bahr el-Ghazal, where malnutrition rates in some places are reaching dangerous levels.

X [lemma=be] VB-reaching Quant(dangerous) NN-transparent(levels|amounts|quantities)

**Comment by bsharpataz** [comment]
[X] is becoming [Quant]

**Comment by bsharpataz** [comment]
perhaps ties into copular correlations.....?
from Doc7, P1: 
```After nearly four years of civil conflict, South Sudan remains one of the most food-insecure countries in the world.```
with edge:
`tester.test(EdgeSpec(food, Correlation, leanSeason)) should be (successful)`
-- correlation for now, but one day may become X-Precedes-Y...?

**Comment by bsharpataz** [comment]
`Cropping conditions are generally favorable in most western areas and central areas due to good performance of seasonal rainfall`
--> `Cropping conditions are generally favorable`

**Comment by Fan-Luo** [comment]
such schemes are untenable due to low repayments

**Comment by Fan-Luo** [comment]
classes of stock are generally in good body condition due to abundant forages

**Comment by bsharpataz** [comment]
Food insecurity is becoming more severe across a wider area and is deepening for people already made vulnerable by displacement and conflict.

**Comment by bsharpataz** [comment]
Seems to be resolved with current pipeline...
