### ISSUE TITLE
Only first sentence in webapp gets a parse at the bottom

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#217]
any chance we can fix that easily? (the table is the same, FWIW) and also btw I really like the table

**Comment by kwalcock** [comment]
I noticed that only the first sentence was diagrammed at the bottom and I was borrowing similar code, so I let it go.  If it looks useful, though, I'll (try to) add it.

**Comment by kwalcock** [comment]
This has been addressed.  The diagram on the bottom has also been extended across the full document.
