### ISSUE TITLE
Canonical name handling formatting-related characters

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#257]
I found that the canonicalName in the JSON-LD output sometimes contains things like list bullet points. I'm sorry I don't understand how canonical names are constructed deeply enough to make this change myself, so I'm just reporting the issue.

Here is a case where the bullet point character is not stripped off in the canonical name:
```jsonld
       "@type": "Entity",
       "@id": "_:Entity_207",
       "labels": [
         "NounPhrase",
         "Entity"
       ],
       "text": "\u2022 The wetter",
       "rule": "simple-np",
       "canonicalName": "\u2022 The wetter",
```

Here is a more problematic case where the actual string is lost and only the bullet point (arrow) character remains as the canonical name:
```jsonld
      "@type": "Entity",
       "@id": "_:Entity_1780",
       "labels": [
        "NounPhrase",
         "Entity"
       ],
       "text": "\u27a4\u27a4 Across Central Asia",
       "rule": "simple-np",
      "canonicalName": "\u27a4",
     ...
```

**Comment by bsharpataz** [comment]
thanks!  feel free to go ahead and assign me

On Mon, Apr 2, 2018 at 12:15 PM, Benjamin M. Gyori <notifications@github.com
