### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#261]
Two runs of, for instance, ExtractFromDirectory, especially in the parallel version, can produce different results.

**Comment by kwalcock** [comment]
So far this is tracked down to potential problems in the StanfordNLP package.  The SequenceGibbsSampler is stateful in

private static Random random = new Random(2147483647L);

and  NERClassifier has

Random random = new Random(2147483647L);

which is only used in training.  However, elsewhere this latter class makes a call to

SequenceGibbsSampler.getRandomSequence(model) which uses random numbers from the first class.

**Comment by kwalcock** [comment]
The above comments are the not cause of the current problem.  See below for the culprit.

**Comment by kwalcock** [comment]
The NER system of StanfordNLP makes use of a WordShapeClassifier which can use several different algorithms.  Some of these algorithms make use of knownLCWords.  LC is for lower case.  This collection is updated in ObjectBankWrapper with the line knownLCWords.add(word);  The system begins with a list of some (around 10,000) lowercase words, which helps it know, for instance, whether a capitalized word at the beginning of a sentence is going to be a named entity or not.  If it was seen that same word before in lowercase, then it was probably just capitalized to start the sentence.

In some of our files we have words like Belt appearing both in uppercase and lowercase.  If the uppercase version is seen first, belt is not in the knownLCWords and Belt gets a shape something like Xxxx.  Since the word was capitalized, it is not added to knownLCWords.  If afterwards, belt appears in lowercase, it might get the shape xxxx, but then be added to knownLCWords.  The next time Belt is seen, it will now have a different shape, because the lowercase version is in knownLCWords, and the shape will be something like Xxxxk.  This change eventually propagates up so that Belt is identified as LOCATION instead of the original O.

This means that if we process a file in the "Belt belt" order, we will get a different answer than in the "belt Belt" order (depending on the rest of the sentence).  This can happen because or parallel processing, because files are sorted in a different order in the file system, because we've added or reordered unit tests, etc.

The word shape algorithms are recorded in stanford-corenlp-3.8.0-models.jar.  In that there is a directory edu/stanford/nlp/models/ner which includes three serialized and compressed models and prop files.  The prop files don't seem to be read, but they record which properties were used to build the models.  They show wordShape=chris2useLC, wordShape=dan2useLC, wordShape=chris2useLC, which make them all sensitive to ordering and other issues of preserved state.

I do not yet know how these models can be rebuilt with wordShape changed to simply chris2 and dan2, which would be the proper solution.  If we can change the StanfordNLP code, the line in ObjectBankWrapper might be commented out.  knownLCWords is exposed in some places and a copy of the original could be kept to replace the version that we want to reset after each run.  It is also possible to turn off the use of word shaping completely with a property (but it won't match the model then).

It looks like a custom version of StanfordNLP with the one line commented out passes all of the tests that were current when I branched.

**Comment by MihaiSurdeanu** [comment]
@kwalcock, this is great detective work, thanks! Before discussing solutions, I think this issue should be filed in the CoreNLP project as well: https://github.com/stanfordnlp/CoreNLP. Can you please do it?

Potential solutions, other than changing the source code of CoreNLP:
1. Implement a custom NER using the Stanford CRF but with custom features. We are already doing this for the bio domain: https://github.com/clulab/processors/blob/master/corenlp/src/main/scala/org/clulab/processors/bionlp/ner/CRFNER.scala. The drawback of this solution is licensing: we are stuck with GPL.

2. Implement a custom NER using our own BiMEMMSequenceTagger with our custom features. We are also doing this in CluProcessor: https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/clu/sequences/NamedEntityRecognizer.scala. The advantages of this strategy are licensing (Apache) and the fact that we control the whole stack. The drawback is that our sequence model and features are slightly weaker than Stanford's.

3. Switch to CluProcessor, which is already doing step 2.

For the reason I discussed over email, I would favor step 3.

**Comment by kwalcock** [comment]
Well, the detective work got to the bottom of it in the end, but there is a fourth solution and I am embarassed not to have realized it earlier.  This comes from directly from Stanford which had already recorded an issue and explanation in 2015 (https://github.com/stanfordnlp/CoreNLP/issues/83).

    props.put("maxAdditionalKnownLCWords", "0");

This can be added to ShallowNLPProcessor.mkNer and possibly some other places like that.  I'll make a PR with a unit test before starting on the switch to CluProcessor.

**Comment by kwalcock** [comment]
The patch has been added to processors and released so that Eidos can readily use it.  That hasn't solved the entire problem, though.  We had noticed earlier that attachments were output in an inconsistent order.  I think they may be added to a set from different threads.  The solution is to order them at some point and I'm doing that just before output.  Afterwards, in testing the 52 files, I still notice a small number of differences in output.  It looks like two rules are finding the very same entity and a different one is being picked on different runs.  For the record, here are two examples involving files 10_FAO_a-i5505e.txt and 21_i8343en.txt:

    "@type" : "Entity",
    "@id" : "_:Entity_49",
    "labels" : [ "NounPhrase", "Entity" ],
    "text" : "rainfall",
    "rule" : "simple-np++quantification2++Decrease_ported_syntax_1_verb",

    "@type" : "Entity",
    "@id" : "_:Entity_49",
    "labels" : [ "NounPhrase", "Entity" ],
    "text" : "rainfall",
    "rule" : "simple-np++quantification2++Decrease_adjective_rule_1++Decrease_ported_syntax_1_verb",

and

    "@type" : "Entity",
    "@id" : "_:Entity_500",
    "labels" : [ "NounPhrase", "Entity" ],
    "text" : "security conditions along the main roads",
    "rule" : "simple-np++Decrease_rule_3++Decrease_surface_VBN",

    "@type" : "Entity",
    "@id" : "_:Entity_500",
    "labels" : [ "NounPhrase", "Entity" ],
    "text" : "security conditions along the main roads",
    "rule" : "simple-np++Decrease_rule_3++Decrease_syntax_verb_agent",

**Comment by MihaiSurdeanu** [comment]
What is actionable here?

**Comment by kwalcock** [comment]
I just need to figure out what the problem is and fix it.

**Comment by kwalcock** [comment]
This was finally handled with #287.  Different rules were output because of attribute ties.  In the extreme case this was of attributes that looked the same (i.e., same trigger) but had different classes.  It would be good to periodically run ExtractFromDirectory on the collection of 52 documents and compare output with a previous version.  Our idea of Attribute identity is somewhat fluid and some comparisons are cursory.
