### ISSUE TITLE
IndexOutOfBoundsException when reading multiple documents

### ISSUE THREAD

**Issue by adarshp** [clulab/eidos#262]
When I try to read the 52 MITRE documents with ExtractFromDirectory, I run into the following error after a certain number of documents are processed.

```
java.lang.IndexOutOfBoundsException: 4
	at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:123)
	at scala.collection.immutable.Vector.apply(Vector.scala:114)
	at org.clulab.wm.eidos.EidosActions.$anonfun$mergeAttachments$4(EidosActions.scala:190)
```
(I have suppressed the rest of the stack trace for readability)

This occurs whether I keep or remove the parallelism in ExtractFromDirectory. The issue seems to be in the mergeAttachments function in EidosActions - in this line:

https://github.com/clulab/eidos/blob/676944d2afde1a4fa75298b98dc34117aca88923/src/main/scala/org/clulab/wm/eidos/EidosActions.scala#L190

the index is out of bounds. Was it @ZhengTang1120 who wrote the function? If so, could you (@ZhengTang1120 ) take a look at it and see what's going on?

**Comment by kwalcock** [comment]
Please continue to pound on it.  Can you remind me where these 52 documents are stored?  Thanks.

**Comment by adarshp** [comment]
It's in the shared Google Drive folder called WorldModelers: https://drive.google.com/open?id=1cHJIfQTr0XE2CEqbo4POSm0-_xzrDP-A

it's under evaluations/6month-eval/mitre-17Feb2018/DocumentSubsetArchive.zip

**Comment by bgyori** [comment]
@adarshp are you running on the txt files that I uploaded here? https://drive.google.com/drive/folders/1ECQNUej2O3_W9NmlA-wyPkwY1UhW_qnD
I have read all of those with Eidos via INDRA (which calls Eidos classes directly rather than the CLI you are using here) and it worked well, though it takes a bit of time.

**Comment by adarshp** [comment]
@bgyori Yes, I am running it on those. When did you run Eidos on the documents? I was able to do it a couple of weeks ago just fine, but when I tried to do it again today I was not able to. The mergeAttachment function where the error seems to be popping up was  first added 6 days ago and has undergone more recent modifications.

**Comment by bgyori** [comment]
I ran them on 3/27 so yeah, it's possible that something changed since then.

**Comment by kwalcock** [comment]
index is valid for attachments, since it comes from attachments.indexOf(mostCompleteAttachments.head)), but it is being used on group instead.  @ZhengTang1120, if this is your code, can you look at it again or let me know you don't have time or something?  Thanks.

**Comment by kwalcock** [comment]
I'm working on a revised implementation and if we get two, we can compare output.

**Comment by kwalcock** [comment]
That should fix the crashing issue.  In the future I'll run through the 52 documents locally before accepting any suspicious code changes, my own in particular.  @adarshp deserves a bug bounty.  Thanks.
