### ISSUE TITLE
ported_token_1_noun-Causal is overall not good

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#264]
I've been systematically looking at extractions and the overwhelming majority of extractions by `ported_token_1_noun-Causal` aren't right. The failures come from actual texts but I could reproduce them on minimal examples in the shell.

The issue seems to be that causal relationships are extracted from non-causal phrases due to inadvertently being triggered by a noun e.g. "IPC _Phase_ Source", "food _aid_ delivery", "several _aid_ agencies", "social _support_ networks", "climate _change_ impacts", "methodological _limitations_ identified", and the list goes on. There are some cases where the phrase does have some sort of a causal influence in it like "fuel options _compound_ food insecurity risk" but even in these cases the cause and effect are assigned in the opposite of what I would expect, (i.e. food insecurity risk _causes_ fuel options, delivery _causes_ food, impacts _cause_ climate, etc.).

While the above examples are not due to this, I also think that this rule is particularly sensitive to messy PDF to text conversions where groups of disconnected nouns can show up next to each other, separated by spaces, even though they don't actually appear in a real sentence.

**Comment by bgyori** [comment]
Having reviewed extractions with the latest version of Eidos, I can confirm that this is still an issue

**Comment by bsharpataz** [comment]
thanks!
