### ISSUE TITLE
Incresed by X percent extracted as a causal relation

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#265]
I guess the pattern here is "A increased by B" being extracted as B _causes_ A but "increase by" is often followed by the magnitude of the increase, not its cause:
- Wheat consumption increased by more than 900 percent
- net sorghum production increased by only 15 percentage points
- wheat increased by 69, 40, and 40 percentage points

These types of sentences shouldn't yield causal extractions.

Similar issues include extractions from sentences like:
- absolute number of IDPs increased by about 250 000 people
- surplus shrunk to only about 15 000 tonnes

**Comment by bgyori** [comment]
This is also confirmed to still be an issue with the current version

**Comment by bsharpataz** [comment]
thanks!
