### ISSUE TITLE
ported_syntax_1c_verb-Causal is overall not good

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#266]
Partly due to #265, which is quite common, but also due to a number of other issues, the vast majority of ported_syntax_1c_verb-Causal extractions are incorrect. Since this rule accounts for ~18% of all extractions, putting some effort into improving it would make a big difference.

I found many cases where a causal relation was warranted like:
- supplementation of work oxen is likely to lead to improved tillage
- job-seekers leading to low real wage levels
- political instability have themselves contributed further to difficulties
- CO2 concentrations will lead to complex
- campaign also contributed to peace and security
- access to food have contributed to political instability

but in each of these cases, the cause and effect were flipped i.e. tillage _causes_ supplementation of work oxen. 

There are also a large number of cases where there isn't a causal relation mentioned but we get extractions from sentences like:
- hunger has spread to locations
- remote rural locations that had limited to no basic services
- searches were limited to publications in Popline

Then I found some cases where the causal relation is essentially correct but the polarity of one of the arguments is incorrect:
- Hot days induced by precipitation -> here "hot days" for some reason comes with a negative polarity

**Comment by bsharpataz** [comment]
thanks, I'll dig into these -- this is helpful!

On Thu, Apr 5, 2018 at 11:58 PM, Benjamin M. Gyori <notifications@github.com

**Comment by bgyori** [comment]
Most of this issue has been resolved as of 93ce22e (everything in the first list above is correct now)! In addition, this rule now only accounts for 5% of extractions. However, the issues I listed in the two latter lists are still there, and so I'm not closing this yet.

**Comment by bsharpataz** [comment]
thanks! very much appreciated!

**Comment by bsharpataz** [comment]
I fixed list 2 with a PR, but couldn't replicate list 3 (i.e., Hot days induced by precipitation).  If you have problems still, can you reopen with another example?
thanks!
