### ISSUE TITLE
Memory requirements and configuration

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#267]
I'm recording this as an issue so that it doesn't take up meeting time and for the record.  Some assignees can also double check to make sure I haven't gone insane.

As @adarshp noticed some time ago and documented nicely on the README.md page, Eidos does not perform well under low memory conditions, and by low I mean a very high low.  One solution is to use the .sbtopts file to increase the maximum memory allowed.  As @hclent once discovered, Travis isn't necessarily happy with that.

The short story is that Travis has been reconfigured to be happy with it and 20 days ago the file slipped out to GitHub and is now in master, with no apparent ill effects.  Travis is now using, instead of a default Amazon EC2 instance with 4GB memory and only 2GB for Java, the GCE from Google with 7.5GB memory.  (See .travis.yml for details.)  Other projects, Processors and Reach, had been doing this all along, unbeknownst to me.  A side-effect of not borrowing their configuration files was discovering how to activate cacheing at Travis, which halved the test time.  Sometimes ignorance has a silver lining.

So, if people have a personal .sbtopts file they have been maintaining, it should no longer be necessary.  Indeed, the file will likely be overwritten with the GitHub version.  I should change some of the documentation in README to describe the new situation.  I'm also double checking whether the exceptions for Windows are necessary.  I still get out of memory with 6GB configured in a different way (along with the appropriately sized heap dump), so maybe .sbtopts was actually being heeded after all.

**Comment by adarshp** [comment]
Thanks for the heads-up, Keith. Looks like it is working fine for me.
