### ISSUE TITLE
Hearst patterns extracted as causal

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#269]
I noticed that the `ported_syntax_noun_Hearst-Causal` rule extracts Hearst patterns that could be useful for finding hyponyms (I just learned about what all this means in the last 10 minutes) but I don't think these should be extracted as `Causal`. For instance,
- dietary alternatives, such as other livestock
- emergency livestock support including provision of feed

currently produce causal relations.

**Comment by bsharpataz** [comment]
Ha! Yeah no joke, guess the “porting” was a bit careless at times... I’ll
def remove/move it soon
