### ISSUE TITLE
broke display of attachments in webapp

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#297]
we now get:
List(NounPhrase, Entity) => production 
     ------------------------------ 
     Rule => simple-np++Decrease_ported_syntax_2_verb 
     Type => TextBoundMention 
     ------------------------------ 
     NounPhrase, Entity => production 
     * Attachments: org.clulab.wm.eidos.attachments.Decrease@1c905409, org.clulab.wm.eidos.attachments.Quantification@b716b2d4 
     ------------------------------

**Comment by kwalcock** [comment]
It looks like I forgot to test something.  Thanks for finding my bug.

**Comment by bsharpataz** [comment]
thanks for everything you do, man!

**Comment by kwalcock** [comment]
Hopefully fixed with #298.  Yell at me if not.
