### ISSUE TITLE
Questionable code for matching brackets and braces

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#300]
This code was copied into Eidos from Processors.  The definition of "match" is in question.  After the first pair, the match is quite loose.  Can @myedibleenso, who GitHub blames for this, explain the intention?  I rewrote it to check for proper nesting, but that may be overkill.  Neither code deals well with things like "We want to 1) do this 2) do that and 3) do the other thing." which doesn't pair the parens.  I wonder if we should keep, remove, or replace.  Thanks.
```scala
  /** Check if brackets and braces match */
  def matchingBrackets(mention: Mention): Boolean = {
    val pairs = Seq(("(", ")"), ("{", "}"), ("[", "]"))
    pairs.forall(pair => matchingBrackets(mention, pair._1, pair._2))
  }

  def matchingBrackets(mention: Mention, opening: String, closing: String): Boolean = {
    val lhsIdx = mention.words.indexOf(opening)
    val rhsIdx = mention.words.indexOf(closing)
    (lhsIdx, rhsIdx) match {
      // no brackets found
      case (-1, -1) => true
      // unmatched set
      case (-1, _) => false
      case (_, -1) => false
      // closing bracket appears before first opening
      case (broken1, broken2) if broken1 > broken2 => false
      // lhs precedes rhs, so count pairs
      case _ =>
        val lhsCnt = mention.words.count(_ == opening)
        val rhsCnt = mention.words.count(_ == closing)
        lhsCnt == rhsCnt
    }
  }
```

**Comment by MihaiSurdeanu** [comment]
The intention of this I think is to make sure each entity has matching parens. I'm not sure how well this works for nested parentheses...

I wonder what we should with Keith's example above. I think in the majority of cases, we do want matchin g parens. Maybe we should detect lists and exclude them?

**Comment by myedibleenso** [comment]
Yes, it was quick and dirty.  Glad you noticed it.  If you've already fix this check, it would be nice to replace what's currently in `processors`.  In any case, it sounds like that particular constraint might not be desirable for what you're doing here in eidos.

**Comment by kwalcock** [comment]
This doesn't seem to have been addressed in processors yet.  I'm moving the issue over there.

**Comment by kwalcock** [comment]
FYI @myedibleenso, the code in processors has been updated.  For each kind of pair (like (), []) there must be proper nesting.  They can be mixed up, however, like ([)].
