### ISSUE TITLE
Changed JSON-LD format

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#301]
The wiki page (https://github.com/clulab/eidos/wiki/JSON-LD) has been updated to show the format of the current master branch as of the merge of pull request #295.  Changes are highlighted and relate to support of multiple groundings.  This issue is so that @adarshp and @bgyori are sure to know about it and have a place to comment.  There are lots of other changes in the pipeline pending discussions with BBN.  If there are too many or they are too fast, maybe we'll have an internal format where you determine the adoption rate.

**Comment by kwalcock** [comment]
I'm hoping that most of these changes are transparent to you, but probably not.  The document text is now included and documentCharPositions is part of the provenance.  Positions in provenance are arrays.  They were supposed to have been before.  If any of this looks temporarily problematic, I can comment out code.

**Comment by kwalcock** [comment]
I may get the attachment/state provenance added, but that may be the limit.  The bigger changes (e.g., merge of Entity, DirectedRelation, UndirectedRelation) have not been ironed out.

**Comment by bgyori** [comment]
Thanks, I'm working on updating the input processor in INDRA for these changes, will post if I run into any issues.

**Comment by bgyori** [comment]
I'm halfway through, the changes are really straightforward and I like the new format!
