### ISSUE TITLE
Clean up README?

### ISSUE THREAD

**Issue by adarshp** [clulab/eidos#303]
Do you plan to keep support for both JSON and JSON-LD output in the future? Perhaps it would be better to clean up the README by removing the JSON output part, especially if it is outdated.

**Comment by kwalcock** [comment]
I'm ignorant of most plans.  The JSON can be useful in testing and real serialization where we have to write something out and read it back in for further processing.  However, it is incomplete and outdated.  It could be kept in the code for our internal use but not advertised on the front page.  I think others who know more about the future will want to weigh in.

**Comment by bsharpataz** [comment]
I kinda like it not being on front page as well, as it changes regularly
with updates to the system.  It also takes a while to scroll through.
Perhaps on another page linked from front page?

**Comment by adarshp** [comment]
I vote for replacing the JSON and JSON-LD output in the README with links to Github wiki pages. In fact, I would suggest deprecating the pure JSON functionality altogether for ease of maintenance.
