### ISSUE TITLE
Running Eidos from JAR via Java

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#323]
In principle it should be possible to use Eidos as a portable JAR without having to have sbt installed and then call it as
```
java -jar /path/to/eidos_fat_jar.jar
```
which currently produces
```
no main manifest attribute, in /path/to/eidos_fat_jar.jar
```
My question is, does anyone know how I could build the JAR such that I can effectively call
```
runMain extractFromDirectory /path/to/input /path/to/output
```
with some appropriate arguments to `java -jar`? Sorry for my ignorance in this matter...

**Comment by bsharpataz** [comment]
check this:
https://stackoverflow.com/questions/45471440/how-to-execute-a-class-with-main-method-which-is-present-in-fatjar-created-by-gr

I've done this in the past -- I think you use the -cp flag to specify the
class path of which main class you're trying to run

**Comment by bgyori** [comment]
Perfect, so
```
java -cp /path/to/eidos_fat_jar.jar org.clulab.wm.eidos.apps.ExtractFromDirectory 
/path/to/input /path/to/output
```
works, thanks!
