### ISSUE TITLE
Extraction of causal paths, preserving implied order

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#325]
While reading some relevant documents, I encountered a very common pattern of "A leads to B via C".  Which implies the causal chain A->C->B.

A real example is:
```
Climate change and natural disasters, it has been argued,
represent a major threat to national and international security 
by increasing resource scarcity and competition and inducing health problems
```
A simple synthetic example to better highlight the issue is 
```
rainfall causes food insecurity by increasing floods
```
for which we currently get "rainfall" -> "food insecurity" and "rainfall -> "flood", equivalent to A->C and A->B given the pattern above. Would it make sense to extract this pattern as A->C, C->B instead? From the perspective of modeling, preserving the causal chain of these relationships would be very valuable.

**Comment by MihaiSurdeanu** [comment]
This is a good one. Thanks!
We'll start on this. Maybe @bsharpataz and I can work on this.

**Comment by MihaiSurdeanu** [comment]
I can confirm that we do not process this perfectly. From the synthetic text above, we extract:

Causes(rainfall, food security)
Causes(rainfall, floods)

when the correct extractions should be:

Causes(rainfall, floods)
Causes(floods, food security)

@marcovzla and @bsharpataz  suggested we add an extra grammar layer that appends the "via C" to previously extracted "A causes B" events. But I wonder if this would work? In this case, you see that the reader actually does extract stuff, it's just not ideal. How would a following layer work in this case? There would have to be an action that removes the incorrect "Causes(rainfall, food security)" in the example above, no?

**Comment by BeckySharp** [comment]
believe it or not @bgyori  -- we now handle this (for non-complex ones, i.e., not for the complicated one with a sprawling parse):
<img width="455" alt="image" src="https://user-images.githubusercontent.com/5384073/75916585-d939f600-5e15-11ea-8a7a-7d2682af1cb5.png">
As of PR #775 ...
