### ISSUE TITLE
Change to processors 7.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/eidos#328]
Processors branch "bettertok2" implements major changes in tokenization. 
Eidos branch "proc740" adjusts eidos to work with this version (7.4.0-SNAPSHOT).

2 out of 405 tests fail in eidos:
sbt 'test-only org.clulab.wm.eidos.serialization.json.TestJSONSerializer'
sbt 'test-only org.clulab.wm.eidos.text.eval6.TestDoc2'

@kwalcock: can you please look at these two?
Additionally, CoreNLP now throws a bunch of warnings (but the code works), which can be seen when running TestDoc2. If you have suggestions on what's causing that, I'd love to hear them. I will investigate this as well. It's most likely something I did in the new processors.

Thanks!

**Comment by MihaiSurdeanu** [comment]
I isolated the CoreNLP component that is generated these warnings. I am looking into it today.

One of the failing tests might be related to an issue in processors. I'll include you @kwalcock in that conversation.

**Comment by kwalcock** [comment]
Is it a local branch of Eidos that is failing?  The one I see here is failing because of a dependency problem.

**Comment by MihaiSurdeanu** [comment]
proc740

(you have to publishLocal processors first)

**Comment by kwalcock** [comment]
I don't see that raw is being included in org.clulab.serialization.json.SentenceOps.jsonAST.  Since it is used in calculating the hash code, it would need to be written and read back in.  raw is empty now when the sentence is read back.  Is that enough of a clue?

**Comment by MihaiSurdeanu** [comment]
I have a rough idea where these come from. I am working on it now.
However, they are triggered in a Stanford component that we do not use currently, so it doesn’t affect Eidos functionality.

**Comment by MihaiSurdeanu** [comment]
I fixed the warnings above.
@marcovzla fixed the JSON test.

The only test that still fails is:
sbt 'test-only org.clulab.wm.eidos.text.eval6.TestDoc2'
@kwalcock, can you please look at this?

Meanwhile, I am merging 7.4.0 into processors master.

**Comment by kwalcock** [comment]
There's a comment for @MihaiSurdeanu at https://github.com/clulab/eidos/commit/8afb4a21feb325619d2a5bd66aa96c307115625c.

**Comment by kwalcock** [comment]
FWIW I haven't forgotten this.

**Comment by marcovzla** [comment]
I believe this relates to #362 since that issue is solved by upgrading to processors 7.4.1

**Comment by kwalcock** [comment]
This is superseded by #414
