### ISSUE TITLE
Output format issue

### ISSUE THREAD

**Issue by ZhengTang1120** [clulab/eidos#354]
There is a format issue in `org.clulab.wm.eidos.apps.MakeMITRETablesFromDirectory`. If the entity we extract contains line break, it will mess up the output tsv.

**Comment by bsharpataz** [comment]
@ZhengTang1120 any chance you can work on this, now in the context of the ExtractAndExport app?

**Comment by bsharpataz** [comment]
I think this is fixed now with the lum.ai normalizeString, we can reopen if needed
