### ISSUE TITLE
Profile the webapp

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#388]
We need to profile the webapp with grounding enabled (i.e. with useW2V=true).  I worked on serializing the ontology and honestly it didn't seem to save much time at all...

@marcovzla suggested that ppl have used https://github.com/clulab/reach/wiki/flight-recorder in the past...

**Comment by kwalcock** [comment]
Thanks for the tip.  Previously I used JProfiler, but the trial period expired.

**Comment by kwalcock** [comment]
Last time I looked at this the conclusion was that not much could be done without changing the code in Processor's Word2Vec.  One problem is that it takes too long to start up because the entire ~5.5GB vector file is processed each time.  Another problem is that the entire dataset of around 2.2 million words is kept in memory the entire time, even though we process far fewer words in each run so that most of the data is never used anyway.

I would suggest indexing the vectors file, making a mapping from the words to the position of the vector in the file, storing this information in a parallel .idx file, and reading this index file when the program starts.  (It could compare file dates and complain if something appears to be out of sync.)  Word2Vec would keep its normal Map[String, Array[Double]], but it would be initially empty (unless, because it looks like the words are sorted based on frequency, the first several hundred are pre-populated).  When a word is looked up, the regular map is checked and the value used if the key is found.  If not, the index is checked, and if found, data for the word is read from the file on demand and transferred to the regular map.  (Maybe if the word frequency is really low and memory is tight, it could be thrown away.)

Anyway, I'd start with some pre-calculation, delayed evaluation, and buffering kinds of things.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock! I like this idea. 
But before we commit, can you please take a look at the loading code? This was written a while ago by a student, and it might be sub-optiomal. Maybe there is something super inefficient there?

**Comment by kwalcock** [comment]
Breaking out the profiler soon...

**Comment by kwalcock** [comment]
@ajaynagesh, it seems like you usually provide the matrices for word2vec.  Our code uses line.split("\\s+") to get at the values, which is relatively expensive.  It looks like the vector files we've been using consistently have a single space as a separator.  If we can change the code to line.split(' '), we'll save significant amounts of time.  Do you think that's safe?  The program will issue a complaint, perhaps unnoticed, if there is a problem, but it will be a pain to deal with.  Can we expect the vector files to be consistent?

**Comment by ajaynagesh** [comment]
@kwalcock: This is part of the Word2Vec library in processors right ? My answer would be if we change this in the library, we could add documentation to make this a requirement (and also make sure we remove extra spaces before creating the matrix). I do not see any other issue in changing to `line.split(' ')`

**Comment by MihaiSurdeanu** [comment]
Good catch @kwalcock. I wonder what the slowdown is when using \\s+ vs. \\s when the file contains a single space as separator...

**Comment by kwalcock** [comment]
If the split can be made on a simple space, then the loading times for the uncached version are lowered significantly, but probably not enough.

52 seconds -> 36 seconds for vectors.txt and
138 seconds -> 95 seconds for glove.840B.300d,vector.txt

on my computer and on the spinning disk.  It's probably worth making that simple code change, but stopping there won't suffice.  Some 2/3 of the remaining time is spend simply parsing the strings into floats.  The binary serialization that Becky did helps with that, but Java serialization is also notoriously slow.  I think we'll have to simply process fewer lines of the files.

**Comment by MihaiSurdeanu** [comment]
Yes, probably not sufficient.

@marcovzla: what was that Spotify library you mentioned?

**Comment by kwalcock** [comment]
Via Ajay and Steve:

https://github.com/spotify/annoy
https://github.com/spotify/annoy-java

I started looking at it yesterday.  Not sure about it  yet.

**Comment by kwalcock** [comment]
Just for documentation of due diligence, if the vectors are serialized and read back in, similarly to the cached ontologies, there's not much to gain and lots to lose:

36 seconds -> 28 seconds for vectors.txt (not much to gain) and
95 seconds -> 280 seconds for glove.840B.300d,vector.txt (lots to lose)

That looks like a dead end.

**Comment by kwalcock** [comment]
Does anyone (@ajaynagesh, @MihaiSurdeanu) know about this Word2Vec.readBinaryMatrix(bytes: Array[Byte])?  It reads in almost the same format as the usual version except that all numbers are recorded as binary in the file.  There is much less parsing this way.  I don't see any code that would produce such a file, but someone wanted to read it in once upon a time.  This may be a more efficient serialization.  FWIW it is also more exact.  The text version seems to be created using "%.6f" which doesn't make use of an entire double and results in lower precision/accuracy, especially for small numbers.

**Comment by kwalcock** [comment]
It won't take long to test.  It's the text version that is questionably accurate.  That data can fit into Floats.  The Doubles we have are overkill for this input.

**Comment by bsharpataz** [comment]
Keith -- thanks for looking into all these avenues fwiw

**Comment by kwalcock** [comment]
So, caching/serialization in the default binary format of a Word2Vec wasn't working, probably because of slow Java serialization.  I think this was largely because of the complicated hash table of arrays that is storing the data.  This data for count words and a vector size of dims can be stored in a single array of floats of size (count * dims).  The list of separate words can be combined into a single string for purposes of serialization.  The single word-list-string and single array of values can be serialized fairly efficiently.  On my computer with a spinning disk (but also being a hybrid drive), I have had times as low as 2 seconds to read the serialized vectors.txt and 7 seconds for glove.840B.300d.vector.txt.  I have seen times up to 30 seconds, though, when it appears that the disk cache was missed.  When running the webapp repeatedly and on a Mac's SSD, I hope that the times will normally be much closer to that 2-7 seconds.  With that in mind, I would like for the time being to stick with the current strategy of reading in the entire vector file over the option of adding a fairly complicated dependency with annoy or a homemade solution that consults the disk incrementally.  Although memory is an issue with this strategy, changing from Double to Float and reducing the number of objects means about half the previous memory footprint.  That's moving in the right direction.  The serialized vector file can be piggybacked on Becky's caching of the ontologies, so there is next to no overhead there.

**Comment by MihaiSurdeanu** [comment]
Nice job! This is awesome.
Yes, let's go with this idea. 
This means writing a converter program that takes the current String-based format and converts it to this efficient format, right?

**Comment by kwalcock** [comment]
It will still read the original text format, but will also write and then read back in the cached, serialized format.  The memory format will change to more resemble the serialized format than the text format.

**Comment by kwalcock** [comment]
@ajaynagesh, are the words in the vector files supposed to include any duplicates?  For glove, there is a repeated, messed-up entry that appears just after "Tayside" and again after "commendations".  This messes up some counting downstream.  I'm expecting the number of unique words to match the number at the top of the file.  Can you check your copy?  Would it be easy for us to use some kind of corrected version?

```
359456258-���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������� 0.00049072 -0.00040844 -0.0016717 -0.0020109 -0.00096432 3.8516e-06 -0.002593 0.00076568 -0.0021061 0.0014609 0.0026364 -0.00033417 -0.00058696 -0.002851 -0.00021612 0.0017742 0.00088459 -0.0026543 0.0011617 0.0001298 -0.00052161 6.7923e-05 0.00043923 0.001908 0.0017352 0.0011448 3.9643e-05 0.00017632 -0.00013885 0.00042351 0.00090963 -0.0028729 0.00087378 -0.0013136 0.0016901 0.00098714 -0.0005398 0.0011082 -0.00013954 -0.00030639 -0.001195 0.00033372 0.00036532 -0.0022014 -0.00070806 -0.0025277 -0.0021394 -0.0008365 -0.00065726 0.002289 0.00032015 0.0013763 -0.0019017 -0.0015794 0.001815 -0.00046465 -0.0013184 0.0014609 -0.0011315 0.00023466 -0.0023807 0.0011148 0.00012426 0.00092353 -0.00049564 0.00075532 -0.0018958 0.00058955 -0.0010577 0.0015661 0.0024304 0.0017282 0.00018434 0.00084461 0.0006478 -0.0013607 0.001271 -0.0018437 -0.00038704 -0.002637 0.0012383 0.0007276 -0.0012114 -0.0018897 0.0017764 0.0014194 -1.4532e-06 -0.00041969 -0.0021308 0.00070943 0.0023248 0.0017151 -4.9551e-06 0.00036195 -0.0016781 0.00099617 0.0015281 0.0019321 0.0023144 -0.0021793 -0.0015828 0.00078813 0.00068886 -0.0032097 9.3061e-05 -0.00014027 -0.0013441 0.00013037 0.0013366 -0.00063155 0.00036739 0.0005632 -0.00036383 -0.001279 0.00022155 0.0021733 0.00041037 -0.00096395 -0.0018174 -0.0011231 0.00070735 -3.2157e-05 -0.00059935 -0.00095389 0.0023884 0.0016507 0.0021134 -0.00045729 0.0015517 0.0023564 0.00059264 -0.0024004 0.00020963 -0.0010305 0.0016861 -0.00092788 0.001415 4.9389e-05 0.0011674 0.0014038 0.00028715 -0.00010389 -0.0020483 0.0011685 -0.00088844 0.00041845 -0.00090435 -0.0003773 0.00016552 0.0012148 -0.00024454 -0.00070173 0.00026348 -0.000253 -0.00034612 -0.001178 -0.00097796 0.00065629 -0.00090754 -0.0032297 0.0008715 -0.0011514 0.00070963 -0.0008338 0.00074096 0.0015855 0.00094803 0.00047195 0.00067179 0.0007352 0.0021031 -0.001464 0.0017704 0.0024671 0.00085704 -0.0013779 -0.0017616 0.00052124 -0.00064736 -0.00022803 -0.00050723 0.00080977 -0.0012796 0.00051347 0.0014855 -0.0021613 0.0018428 0.0023641 0.0012746 -0.0019798 -0.0012595 -8.8058e-05 0.001108 0.00023353 -0.00072072 -0.0012789 0.0013453 0.0017101 0.00051302 0.0017507 0.0003149 0.00017823 -0.0026571 0.002127 0.00045788 -0.00061061 -0.00052926 -0.0012826 -0.0012285 0.00057567 0.002042 0.00057503 0.00059972 -0.0018889 0.0013202 -0.00088423 -0.00020368 0.0029658 -0.00012263 0.00074725 -0.0020057 -0.00049893 -0.00079399 0.0010785 0.0005825 -0.0005795 0.00096027 0.00213 -0.0025004 0.00067594 -0.00022545 -0.0014568 0.0008125 -0.00013832 -0.00010219 0.0009906 0.00039688 0.0015999 -0.0022681 -0.00053253 0.0029344 -0.00018066 5.948e-05 -0.0026229 0.0019122 -0.0025157 0.0024548 0.00023318 -0.00016205 -0.0019386 0.00067449 -0.0014495 -0.00062247 -7.6669e-05 -0.00028727 0.0013738 -0.00034971 0.00041364 -0.0018286 0.0017501 0.00204 -0.00099393 0.0019768 -0.0018731 -0.002169 -0.0010001 -0.0021641 -0.00018038 0.00046083 -0.00099222 0.0014967 -0.0032341 0.0020379 -0.0018642 0.000495 0.00065514 0.00040651 -0.00070927 -0.0027163 0.0020992 -0.00012049 0.0020023 0.00050012 -5.3189e-05 0.001176 0.00099838 -0.0016051 0.00019555 0.0017695 0.00017307 -0.00023782 -0.00055435 -0.0017517 -0.00010359 1.7239e-05 0.00031925 0.0027949 -0.00066141 0.00113 -0.00046436
364494534-���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������� -0.00016985 -0.0012435 0.0027223 0.0010433 0.0014608 0.00095341 0.0001709 -4.4106e-05 -0.00088374 -0.0018877 -0.0020914 -4.7104e-05 -0.0023001 -3.8082e-05 -0.002699 -0.00054832 0.0011046 -0.0015685 -0.00099343 -0.0011067 0.00015359 -4.2602e-05 -0.0014011 -0.00038671 -0.00065607 -0.0029043 0.00036069 -0.0019528 -0.00084425 -0.00071087 -0.00060168 0.00030607 0.0027666 0.001398 -0.0010901 0.0013639 0.0032535 -0.0014177 0.0014763 0.0005451 0.00056159 -0.00099353 0.0025781 0.00020633 -0.00091141 -0.0023204 0.0012798 -0.00085074 -0.00040349 0.0029745 -7.6401e-05 -0.00045163 -0.00092596 0.0029684 -0.00031249 -0.0010553 0.001158 0.0014272 -0.0010856 -0.0020856 -0.0017883 0.00041746 0.0025521 0.00093966 0.0016337 -0.00090362 -4.3221e-06 0.0014643 -0.0023571 0.0021804 0.001226 -0.0014233 -7.7158e-05 -0.00032153 -4.7408e-05 0.0013356 -0.00091127 0.00091618 -0.0018659 0.0013032 -0.0013419 0.0016707 0.0013339 -0.00020566 -0.0023539 -0.00094328 0.0031492 -0.00070353 -0.0013508 0.0019972 -0.0016305 -0.00063363 -0.00047022 0.00074004 -0.0017831 -0.0019494 0.0022062 0.00078436 -0.0011122 -0.00013975 0.00033341 -0.00059491 -0.0011464 -0.0020762 -0.001455 -0.00096554 -0.00070447 0.00084753 0.0016062 0.00080941 -0.00095373 0.00076756 -0.001311 0.00074045 0.00010489 -0.00073168 -0.0017724 0.0013463 -0.001658 0.00071759 -0.00080313 -0.00053907 0.00049669 0.0019571 -0.0001752 -0.00057443 0.0021029 0.0010204 -0.0022626 -0.0010184 -0.0025391 -0.00094667 -0.00038691 0.00075131 -0.00069243 -0.0023308 0.00078641 0.00026665 -0.00089139 -0.00012435 -0.0007145 0.00047753 0.00059758 0.0016265 -0.0014498 -0.00028492 -0.0018053 0.0017326 -0.0017324 0.00076005 -0.0019078 0.001135 -0.0026302 0.00020644 0.00028763 0.0016695 -0.00050203 0.0022192 0.0016309 -0.00074276 0.00091777 0.00048985 -0.001803 -0.0019976 -0.0024297 -0.0024346 0.0013931 -0.0013919 -0.00056922 0.0019766 0.0002196 0.0005308 0.00064171 -0.00012046 0.00049637 -0.0017952 -0.0015759 -0.0014005 0.00049439 0.0007194 0.00026604 3.0883e-05 0.001095 0.0017253 -0.00067273 -0.00031455 -0.0012661 -0.00075671 0.00012831 0.00027861 0.0029751 0.00092835 -0.0012288 -0.0026872 0.0006594 -0.0012985 -0.003108 0.001003 0.00084986 -0.00042804 0.0014121 0.0020655 0.00074933 -0.001854 -0.003061 -0.0010635 0.00030231 -0.00024822 -0.0009867 -0.00046532 0.00016542 -0.0017447 -0.0014121 0.002201 0.00045087 0.00074823 0.0029384 -9.1752e-05 0.0021972 0.00045395 0.00039152 0.0001219 -0.00063783 0.00056645 0.0015583 -0.0012679 -0.0012204 -0.0010784 -0.0018436 0.00086488 0.0013752 0.00016925 -0.00050095 0.0014557 -0.00078012 -0.0010107 -0.0014029 -0.0013195 0.0001707 -0.00043635 -0.00060421 0.0023249 -0.00061169 -0.00016193 -0.0027234 9.2902e-05 -0.0027038 0.0010439 -0.000807 0.00031063 -0.00063063 -0.001678 -0.0003198 -0.0024729 -0.0022925 0.0028355 -0.0015863 0.001216 0.0022935 -0.00235 -0.00081959 -0.00014264 0.002097 0.00054239 -0.0011349 -0.0013261 0.0027778 0.00017102 -0.00055158 -0.0023083 0.00077534 -0.0016531 0.0002878 0.00036925 -0.0014679 -0.00099478 -0.00066659 0.00035471 0.0021503 0.0016447 0.00012019 0.00051851 -0.0028608 -0.00049265 -5.4445e-05 0.0020279 0.001482 0.0026767 0.0032164 0.00047487 0.0017332 0.00026942 -0.00017124 -0.0015688 0.0023475 0.0012299 -0.00065489 0.00071386 -0.0013968 -0.0015977
```

**Comment by ajaynagesh** [comment]
@kwalcock .. checking this locally .. will report to you soon...

**Comment by ajaynagesh** [comment]
@kwalcock : I downloaded a fresh copy of GLoVe embeddings and checked that those messed up entries are present in the freshly downloaded file as well. Strange!

**Comment by kwalcock** [comment]
Drat.  That means that I have to find a way to deal with them.  Thanks very much for checking.

**Comment by ajaynagesh** [comment]
Those are the only 2 words (after Tayside and commendations) which contain those junk characters. Perhaps they are some unicode encoded words which are non-printable. Can we ignore those 2 lines if it is messing up our downstream processing ? I think we can. @MihaiSurdeanu, @marcovzla, @bsharpataz ? 

We could have to appropriately correct the header file. It will now be `2196015 300` instead of `2196017 300`

**Comment by kwalcock** [comment]
It's not very far downstream.  It's probably easier for me to deal with so that we can use it unchanged.  There will just be an ugly hack in the code.

**Comment by kwalcock** [comment]
In isolation, the smaller vectors completely processed can take as little as 4 seconds and the glove file 10 seconds.  However, seeing that while working on the webapp is doubtful.  There I see more like 15 and 35.  @bsharpataz (or anyone else) would you care to test the kwalcock-CompactWord2Vec branch?  You'll need to run CacheOntologies once first as well as edit the eidos.config file.

**Comment by kwalcock** [comment]
@MihaiSurdeanu, @bsharpataz, here's some documentation about how this works for Eidos.

During the building of the ontologies, Eidos calls `wordToVec.makeCompositeVector(ontologyNode.values)`.  This method creates just a single array, adds the values associated with all the values/strings to that array, and then normalizes it in place.  v.get returns not an array, but an index into the larger array, and add just uses the index to pick out the correct values.

```
  def makeCompositeVector(t:Iterable[String]): Array[Double] = {
    val vTotal = new Array[Double](dimension)

    for (s <- t) {
      val v = map.get(s)
      if (v.isDefined)
        add(vTotal, v.get)
    }
    Word2Vec.norm(vTotal)
    vTotal
  }
```
Eidos uses some other Word2Vec methods, but there is only one other time when an Array is created and it is there presently only for testing in Eidos.  It allowed me to run the CompactWord2Vec and Word2Vec side by side and compare their values.

```
  def get(word: String): Option[CompactWord2Vec.ArrayType] = {
    if (map.contains(word)) {
      val offset = map(word) * dimension
      val vec = new CompactWord2Vec.ArrayType(dimension)

      for (i <- 0 until dimension)
        vec(i) = array(offset + i)
      Some(vec)
    }
    else None
  }
```
A potential problem is that Word2Vec in processors has this public function getWordVector which returns an Array of Doubles, a reference to its internally stored values.  (Perhaps this was also only for testing.)  The new version does not store values like this and would have to generate them with the function above.  If this public method is called often, even by some Java program we don't know about, then there will be an efficiency problem.

```
  def getWordVector(word:String):Option[Array[Double]] = {
    val sw = Word2Vec.sanitizeWord(word)
    matrix.get(sw)
  }
```

**Comment by kwalcock** [comment]
P.S.  Array[Double] has been kept for compatability reasons.  The internal Word2Vec storage is for Floats.  If MeSH is so terribly large, then space could be saved by using the Floats for the ontology as well.

**Comment by kwalcock** [comment]
On a Mac with an SSD time for reading the glove embeddings went from 99 seconds to 12 seconds.  That's still rather long, but in the right direction.  I'm going to PR it.

**Comment by kwalcock** [comment]
Between PRs #422 and #431, this should be in good shape.
