### ISSUE TITLE
quantification1 pulls out quantifier as part of entity

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#39]
In attempting to fix test 8 in p6s2, I found that `quantification1` in entityQuantification.yml pulls out the quantifier along with the noun that it applies to. E.g. "poor" is included in "poor access to services", whereas I would have expected this entity to just be "access to services":
```
List(NounPhrase, Entity) => poor access to services
	------------------------------
	Rule => simple-np++quantification1
	Type => TextBoundMention
	------------------------------
	NounPhrase, Entity => poor access to services
	  * Attachments: Quantification(poor)
	------------------------------
```
Am I right that this is a problem? Or is the quantifier supposed to be part of the entity?

**Comment by MihaiSurdeanu** [comment]
I think this should have been picked up as a DEC event. @bsharpataz?

**Comment by bsharpataz** [comment]
No, it should not be part of the entity, check to see if “poor” is one of
the things being avoided in aviodLocal.  Triggers need to be present in
both places, in the main grammar to be used for an inc/dec event and in
avoidLocal to not be included in the entity.  If that’s not the problem,
you can let me know

**Comment by bsharpataz** [comment]
I think this was fixed, no?  If not, you can re-open

**Comment by bgyori** [comment]
The specific instance was fixed but I think the more general fix would be to take every entry in Quantifiers.tsv and add to the ignore list.

**Comment by bsharpataz** [comment]
Oh, I see.  Well, it is, essentially.... which makes me wonder a little now
about the original error...  but to your point --
The system is designed so that the quantifiers are labeled by the lexicnNER
and everything with that label is avoided (with this rule:
https://github.com/clulab/eidos/blob/master/src/main/resources/org/clulab/wm/grammars/avoidLocal.yml#L55-L61).
