### ISSUE TITLE
Ontology Diagnostic Tool

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#394]

**Comment by bsharpataz** [comment]
- brainstorm and add a bunch of visualizations
- cluster based on what grounds to what?
  -- homogeneity of clusters?
  -- size of clusters?
 -- where are the clusters in relation to each other? i.e., if we "cluster" the clusters, does it highlight some too dense areas that need more disambiguation?

**Comment by BeckySharp** [comment]
this will be handled in taxero
