### ISSUE TITLE
Make reference.conf

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#406]
This is Marco's idea, I believe, and this is here to ensure that the good idea is not forgotton...

Is this change below still in the works?

"One thing I would like to do is to store all the config defaults in a file called reference.conf instead of hardcoding them in EidosSystem. This would allow us to use variables even in the defaults. An explanation of the utility of a reference.conf can be found here: https://github.com/lightbend/config#standard-behavior    Basically, scala-config reads the variables from several sources, each with lowest priority, and leaves reference.conf as the last option, which is intended to be the library defaults."

Becky just made a very nice Ontology cache, but part of it involves duplicating code like

val unOntologyPath: String = getArgString("EidosSystem.unOntologyPath", Option("/org/clulab/wm/eidos/ontologies/un_ontology.yml"))

which your proposal will make unnecessary.  So, it might be nice to add this in the nearer future.  I'm going to at least add a note to the PR as a reminder.

**Comment by bsharpataz** [comment]
is this closed with PR #428 ?

**Comment by kwalcock** [comment]
Yes.
