### ISSUE TITLE
Do not expand entities across clauses?

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/eidos#44]
Becky,

We now expand entities across clausal dependencies. For example, in this sentence:
https://github.com/clulab/eidos/blob/master/src/test/scala/org/clulab/wm/CAG.scala#L27
the 3rd entity is "livelihoods being decimated", when it should probably be "livelihoods".

**Comment by ZhengTang1120** [comment]
level of acute malnutrition -- test changed to match current "intended behavior," so will need to modify tests when issue closed

**Comment by bsharpataz** [comment]
food insecurity in Unity
