### ISSUE TITLE
we should def update the readme... it's what people see when they look at us! 

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#482]
- we should *not* advertise the no-longer-super-supported JSON
- we SHOULD super emphasize the webapp!
- we should direct people to ExtractAndExport
- we should mention the Portuguese support
- we should add the CacheOntologies step?
- we should include any other Keith coolness I am forgetting?

other changes @MihaiSurdeanu ?

**Comment by MihaiSurdeanu** [comment]
I support this message :)

**Comment by brandomr** [comment]
I agree! One of the things that @jgawrilo and I have been trying out is using the webservice with requests (instead of the UI). I was able to send text to the webservice with something like:

```
text = """A significant increase in precipitation resulted in food insecurity and
a decrease in humanitarian interventions. Actually, food insecurity itself can
lead to conflict, and in turn, conflict can drive food insecurity.
Generally, humanitarian interventions reduce conflict."""

webservice = 'http://localhost:9000'
res = requests.get('%s/parseText' %webservice, params={'text': text, 'cagRelevantOnly': 'true'})

json_dict = res.json()
print(json_dict['syntax'])
```

I think that the documentation should include reference for doing this. Am happy to make that update in a fork @kwalcock if that's helpful?

**Comment by MihaiSurdeanu** [comment]
@kwalcock: can you please work on the readme?

**Comment by kwalcock** [comment]
@brandomr, that sounds great to me.  I had no idea that people were using it like this.  You are more than welcome to it, especially if you can package it in a PR.  I also appreciate the working example code and will borrow that if necessary.  Thanks.

**Comment by brandomr** [comment]
@kwalcock submited a [PR](https://github.com/clulab/eidos/pull/484) and added some comments/context around it.

**Comment by kwalcock** [comment]
FWIW here's the outline I'm working on.

- Running Eidos
	- Using the Sample Apps
		- Webapp
			- Interactive use
			- (Include a screen shot)
			- Automated use
			- (Add recent code sample)
		- Shell
		- ExtractAndExport
	- Using the Scala API
		- Prettified display
		- Export to JSON
- Connecting Eidos
	- Indra
	- Delphi
- Working with Eidos
	- Compiling
	- Configuring
		- Vector files
		- Ontologies
	- Optimizing
		- CacheOntologies
	- Translating
		- Portuguese
	- Integrating
		- (How to include in another project)
- Notes
- License

**Comment by bsharpataz** [comment]
yay! love the outline!

**Comment by MihaiSurdeanu** [comment]
Beautiful.

**Comment by kwalcock** [comment]
The updated readme was merged recently, so I'm going to close this.
