### ISSUE TITLE
Time normalization picking up artifacts

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#495]
When reading documents, I sometimes get artifactual timex extractions like from the sentence
```
This document updates the IPC projections made in December 2015 , available here :  
http://www.ipcinfo.org/ipcinfo-detail-forms/ipcinfo-map-detail/en/c/379480/
```
in the document IPC_SouthSudan_Acute_FI-Situation_April_2016.txt we get
```
49063       }, {
49064         "@type" : "TimeExpression",
49065         "@id" : "_:TimeExpression_34",
49066         "startOffset" : 14189,
49067         "endOffset" : 14195,
49068         "text" : "379480",
49069         "intervals" : [ {
49070           "@type" : "TimeInterval",
49071           "@id" : "_:TimeInterval_34",
49072           "start" : "+379480-01-01T00:00",
49073           "end" : "+379481-01-01T00:00",
49074           "duration" : 31622400
49075         } ]
```
If this is something that could be improved or at least worth looking into on the reader side, I can send a longer list of examples, otherwise, feel free to close the issue!

**Comment by kwalcock** [comment]
That's a keen eye you have.  It looks like `"text" : "379480",` should be `"text" : "December 2015",`.

**Comment by EgoLaparra** [comment]
This seems to be a mistake from the temporal parser that identifies "379480" as a year. There is not much we can do for the moment. We are working on an improved version of the model that, hopefully, will be integrated into eidos soon.

**Comment by EgoLaparra** [comment]
Yes, they could help us to perform error analysis. Thanks.

**Comment by bgyori** [comment]
Okay, I emailed you a log with all the invalid entries from the evaluation corpus, I'll close the issue here.
