### ISSUE TITLE
Print syntactic dependencies in RAPShell

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#51]
I would love to see the syntactic dependencies printed in the RAPShell (though I know it's available via the web interface). After some digging, I found that the reason dependencies aren't currently displayed is that this line is commented out: https://github.com/clulab/eidos/blob/09e717b6a042e75c9d4544eb29567c4ac76e0a68/src/main/scala/utils/DisplayUtils.scala#L17
Shall I uncomment it in a PR, or is there a good reason not to do that? Thanks!

**Comment by MihaiSurdeanu** [comment]
@kwalcock, @bsharpataz?

**Comment by kwalcock** [comment]
I should look through the file history and see why it was commented out.
There may have been a good reason for some need unknown to me.

**Comment by kwalcock** [comment]
This line was commented out since the beginning, when it was copied over from wmseed.  It is only called from demoWMseed in a file "Created by ajaynagesh on 5/31/17".  Does that output matter to someone?

**Comment by bsharpataz** [comment]
I was not the original writer of the method, but I think that they are
likely commented out bc (a) they're looooong, and clog the output quickly
and (b) often with long sentences they usually end up truncated anyway
(though perhaps not the way it's called?)

I am pretty indifferent either way -- maybe we can add a user option at the
loading of the RAPShell where user can decide which way to go? or is that
overly complicated?  If we change it there, it will show up in the webapp
too, and i'd rather not have it all there, unless maybe @kwalcock can be
awesome and add a javascript collaps-y window thing with the info?

**Comment by kwalcock** [comment]
Well, a fairly simple textedit control like the one I'm typing in is resizeable and scrollable and could prevent some output from getting too long.

In general, no toString() will make everyone happy.  Perhaps people can customize locally?  I would just perform inspection in the debugger.

**Comment by bsharpataz** [comment]
as a compromise, perhaps you can add a simple print in RAPshell (as that's
largely intended to be an "internal" debug tool) rather than uncommenting
the line in displayMentions which is called prolifically throughout the
repo...?

**Comment by kwalcock** [comment]
Sounds good if that suits bgyori.  I'll figure out how to add it to the RAPshell only.

**Comment by kwalcock** [comment]
Great!
