### ISSUE TITLE
What happened to the webapp?

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#515]
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/5384073/48749955-48e49b80-ec3a-11e8-9e9a-3208944040d7.png">

does it still work for you @kwalcock ?

**Comment by kwalcock** [comment]
It took me some time to realize that the diagram is missing.  No, it's not there for me, either.

**Comment by bsharpataz** [comment]
ok, per @marcovzla I commented out lines 417 (@EgoLaparra) and 418(@vikas95):
```
//      "timexs" -> mkJsonFromTimeExpressions(time),
//      "geoexps" -> mkJsonFromLocationExpressions(location),
```

and it works again!
<img width="375" alt="image" src="https://user-images.githubusercontent.com/5384073/48751560-4128f500-ec42-11e8-967a-b11660602cac.png">

so....... hope that helps the debug.

**Comment by kwalcock** [comment]
Yes, that's the problem spot, but then you won't see the time or locations.  I've almost got it.

**Comment by kwalcock** [comment]
The fix is working its way through Travis.  I recall you saying that you'd make me fix it and indeed you did.

**Comment by EgoLaparra** [comment]
Sorry, I'm late. Thank you for solving this Keith.

**Comment by kwalcock** [comment]
It was my error, @EgoLaparra, but do you know how the geolocations are supposed to appear in the diagram?  I've never seen one.

**Comment by EgoLaparra** [comment]
They shouldn't appear. That part is not implemented yet.

**Comment by marcovzla** [comment]
this was fixed in #516 right?

**Comment by bsharpataz** [comment]
I think so! thanks!

**Comment by bsharpataz** [comment]
yep, I think so thanks!
