### ISSUE TITLE
Two farming entries in UN ontology

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#528]
There is both an `events/human/agriculture/farming `(https://github.com/clulab/eidos/blob/master/src/main/resources/org/clulab/wm/eidos/english/ontologies/un_ontology.yml#L711-L721) and an `events/human/farming` (https://github.com/clulab/eidos/blob/master/src/main/resources/org/clulab/wm/eidos/english/ontologies/un_ontology.yml#L1250-L1254) entry, aren't these redundant?

**Comment by bsharpataz** [comment]
yes, I will fix after the hackathon thanks!

**Comment by kwalcock** [comment]
It looks like one is an event now and the other an entity.  Has this issue been cleared?

**Comment by BeckySharp** [comment]
Kinda, it will be “cleared” with the unified ontology with BBN we’re working on.
