### ISSUE TITLE
Provision of duplicated in intervention ontology

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#560]
In the internvetion ontology, many entries have "provision of" duplicated in their name and examples, e.g. "provision of provision of non-formal education". For instance there are several examples in this section:
https://github.com/clulab/eidos/blob/master/src/main/resources/org/clulab/wm/eidos/english/ontologies/interventions.yml#L157-L182
I just want to confirm this is not on purpose. I'll PR a fix if it's confirmed that this is a problem.

**Comment by bsharpataz** [comment]
yeah -- it's not on purpose, and feel free to fix.  it comes from the way it was scraped from the kimetrica data, but please go ahead and delete!
