### ISSUE TITLE
Can't cancel Jenkins test

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#608]
There is a Jenkins job http://jenkins.cs.arizona.edu:8090/job/eidos/job/PR-606/2/ which seems to have hung.  The UI apparently has a way to deal with this, but perhaps only if the user has some special permission to cancel things.  The closest I can get is by trying to use the rest interface (http://jenkins.cs.arizona.edu:8090/job/eidos/job/PR-606/2/stop) which leads to the message
```
Access Denied
clulab is missing the Job/Cancel permission
```
Can someone, @EgoLaparra, look into this but iff they are back on duty?

**Comment by MihaiSurdeanu** [comment]
I killed it.
I (or Egoitz) can share the admin password with you for jenkins. But I
would not do it over email. Any other way to contact you?
