### ISSUE TITLE
Dockerfile fails to install 'oracle-java8-installer' package

### ISSUE THREAD

**Issue by adamocarolli** [clulab/eidos#611]
The docker build fails to complete with the following error:

```
Package oracle-java8-installer is not available, but is referred to by another package.
 This may mean that the package is missing, has been obsoleted, or is only available from another source
 E: Package 'oracle-java8-installer' has no installation candidate
```

The likely cause is that the PPA used `webupd8team/java` has been discontinued permanently due to a breaking update in the Oracle JDK license on April 16th, 2019 (See http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html)

**Comment by kwalcock** [comment]
Thanks for filing the issue *and* the PR to fix it!
