### ISSUE TITLE
Representing modifiers of Migration arguments in JSON-ld

### ISSUE THREAD

**Issue by chanys** [clulab/eidos#613]
During the recent TA1 hackathon, we discussed representing certain properties of `Person Group` for Migration events. I believe these are:
  * Value (number of people): Absolute, Daily, Weekly, Monthly, Percentage (of some other numbers)
  * Modifier: NoModifier, Min, Max, Approximate

We (BBN) are wondering whether you have though about how to represent them in JSON-ld (so that UA and BBN can be consistent in representation format, which makes things easier for Ben G.). 

For instance, given a text snippet with a Migration event "A total of 1,418 South Sudanese refugee arrivals", we are currently capturing arguments in the JSON-ld like so (and according to the `Argument` row in https://github.com/clulab/eidos/wiki/JSON-LD , this agrees with UA's format as well):
```
           "arguments": [
                {
                    "@type": "Argument",
                    "type": "actor",
                    "value": {
                        "@id": "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1"
                    }
                }
            ],
```

We are thinking of the following as a plausible representation, i.e. by adding a dict:
```
           "arguments": [
                {
                    "@type": "Argument",
                    "type": "actor",
                    "value": {
                        "@id": "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1"
                    },
                    "number": {
                        "value": # this is an integer
                        "rate": # possible string values are: Absolute, Daily, Weekly, Monthly, Percentage
                        "modifier": # possible string values are: NoModifier, Min, Max, Approximate
                    }
                }
            ],
```

Or would breaking up makes better sense, something like?
```
{
    "min_val":[INT/FLOAT/FIELD_NON_EXIST],
    "val":[INT/FLOAT/FIELD_NON_EXIST],
    "max_val":[INT/FLOAT/FIELD_NON_EXIST],
   ...
}
```

Some more questions:
* If a field is non-existent, e.g. if the text snippet is just " South Sudanese refugee arrivals", what to use: NONE, FIELD_NON_EXIST, etc.?
* In the above, the field `rate` contains normalized values/strings like "Absolute", "Daily", etc. Are we interested in capturing the underlying text as well, e.g. like "the daily average".
* We are wondering how do you deal with texts such as "thousands". Normalize it to `modifier=Approximate` and `value=5000`?

Yee Seng, from BBN.

**Comment by bnmin** [comment]
Thanks! @chanys 

@bgyori @BeckySharp @MihaiSurdeanu We'd love to hear your thoughts on this. We hope to converge on a shared format that INDRA can take as input. Thanks!

**Comment by kwalcock** [comment]
I wasn't especially involved in that discussion, but will probably end up implementing this output, so here are some questions anyway:

An extraction has some arguments and it looks like this actor is one of them, looking well-formed.  The number part is new.  Is it describing more the actor or more the entire extraction?  If it is modifying the actor, shouldn't it be an argument or state of `"@id": "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1"` and be specified there?  I imagine something like
```
<extraction for migration event?>
           "arguments": [
                {
                    "@type": "Argument",
                    "type": "actor",
                    "value": {
                        "@id": "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1"
                    }
                }
            ],

<extraction for "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1">
           "states": [
                {
                    "@type": "State",
                    "type": "count",
                    "text": "123",
                    "value": 123.0
                },
                {
                    "@type": "State",
                    "type": "rate",
                    "text": "every seven days",
                    "value": Absolute|Daily|Weekly|Monthly|Percentage
                },
                {
                    "@type": "State",
                    "type": "modifier",
                    "text": "at most",
                    "value": NoModifier|Min|Max|Approximate
                },
            ],
```

We do have some things like TimeExpression or TimeInterval and GeoLocation that are found in Sentences and can then be referred to in States.  Maybe call it a Measurement.

|Name|Property|Type|Description|
|---|---|---|---|
|Measurement|@type|"Measurement"|It has some numbers with units and "modifiers"|
||@id|IRI|and is provided with an ID.|
||startOffset|integer|It has a starting, zero-based character offset into the sentence text,|
||endOffset|integer|and an ending, exclusive character offset,|
||text|string|along with the actual text determined by the offsets,|
||value|double|and some numbers.|
||units|Unit|some potential units like a rate,|
||modifier|Mod|and some potential modifier,|

Unit = Absolute|Daily|Weekly|Monthly|Percentage
Mod = NoModifier|Min|Max|Approximate

```
sentences:
           measurements: [
                {
                    "@type": "Measurement",
                    "@id": "measurment_id",
                    "startOffset": 4,
                    "endOffset": 10
                    "text": "total of 1,418 ",
                    "value": 1418.0,
                    "units": Absolute,
                    "modifier": Total
                },
           ]

<extraction for "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1">
           "states": [
                {
                    "@type": "State",
                    "type": "MEAS",
                    "text": "total of 1,418 ",
                    "value": {@id(measurment_id)}
                },
```

* If a field is non-existent, e.g. if the text snippet is just " South Sudanese refugee arrivals", what to use: NONE, FIELD_NON_EXIST, etc.?

In general, we've been suppressing the output of empty, nonexisting values.  They aren't even mentioned in the output.

* In the above, the field rate contains normalized values/strings like "Absolute", "Daily", etc. Are we interested in capturing the underlying text as well, e.g. like "the daily average".

The first suggestion above fits this better, but it could be added to the send.

* We are wondering how do you deal with texts such as "thousands". Normalize it to modifier=Approximate and value=5000?

To my knowledge this is not in Eidos yet.  Perhaps it is something soon to be incorporated.


Someone will set me straight momentarily, I'm sure.

**Comment by kwalcock** [comment]
PS.  See also #594.

**Comment by kwalcock** [comment]
I'm finally putting two and two together.  In addition to the discussion from #594 that describes where migration fits on this (https://github.com/clulab/eidos/wiki/Anatomy-of-Mentions) table,  there needs to be an update of the jsonld documentation (https://github.com/clulab/eidos/wiki/JSON-LD) for the migration event.  I'll add that in bold and it will look like the third table below.  Some of the Arguments can have States.  One of these is called "counts" internally and I implemented an export function at the hackathon.  These show up in the jsonld as in the first two tables below, which I will also add to the jsonld page.  These are rough drafts.  In order to get this count state to fit into the schema, it is a little different from the other states whose value_types were simpler.

Here is the state:

|<a id="StateType">State type</a>|<a id="ValueType">Value type</a>|Notes|
|---|---|---|
|INC||Indicates that the Concept has been increased.|
|TIMEX|{@id(TimeExpression)}|This is an ID referring to a time expression.|
|<b>COUNT</b>|<b>Count</b>|<b>Indicates some numeric value.</b>|

The value type is not empty or a reference, but this:

|Name|Property|Type|Description|
|---|---|---|---|
|<b><a id="Count">Count</a></b>|<b>@type</b>|<b>"Count"</b>|<b>A count is typed.</b>|
||<b>value</b>|<b>double</b>|<b>It has a numeric value,</b>|
||<b>modifier</b>|<b>"NoModifier", "Approximate", "Min", or "Max"</b>|<b>a possible modifier,</b>|
||<b>unit</b>|<b>"Absolute", "Daily", "Weekly", "Monthly", or "Percentage"</b>|<b>and a possible unit.</b>|

Here is that extraction with its arguments.

|<a id="ExtractionType">Extraction type</a>|<a id="ExtractionSubtype">Extraction subtype</a>|Argument type|Notes|
|---|---|---|---|
|"relation"|||Link between concepts|
||<b>"migration"</b>||<b>This is an undirected relation.</b>|
|||<b>"group"</b>|<b>Who,</b>|
|||<b>"moveTo"</b>|<b>where to,</b>|
|||<b>"moveFrom"</b>|<b>where from,</b>|
|||<b>"moveThrough"</b>|<b>where through,</b>|
|||<b>"timeStart"</b>|<b>starting when,</b>|
|||<b>"timeEnd"</b>|<b>ending when,</b>|
|||<b>"time"</b>|<b>and?</b>|

These who, where, etc. will refer to other extractions.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock!

This looks good. My only comment is that `modifier` and `unit` are always present, so they are not "possible" modifiers/units.

**Comment by kwalcock** [comment]
That makes sense given the enums in the code.  Absolute must be more or less NoUnit, I guess.  For the migration extraction are we not going to try to reuse the TimeInterval from https://github.com/clulab/eidos/wiki/JSON-LD#user-content-timeinterval ?  timeStart and timeEnd are obvious, but is the last time (next to and?) a duration?

**Comment by chanys** [comment]
Thanks @kwalcock . Sorry for replying late. My initial hesitation about specifying the number extraction on the Actor, is if we have something like "1,418 refugees arrive daily", then it seems the "daily" is more a property of the event & actor in combination, rather than just on the "refugees" actor. But I agree it is probably fine either way, and specifying it on the Actor makes the representation simpler. So let's go with that. 

So if I understand you correctly, it will look something like the following:
```

sentences:
    "counts": [
        {
            "@type": "Count",
            "@id": "Count-123",
            "value": 1418.0,
            "modifier": NoModifier/Approximate/Min/Max,  # in this case, NoModifier
            "unit": Absoluate/Daily/Weekly/Monthly/Percentage, # in this case, Daily
            "text": "1,418 refugees arrive daily",
            "provenance": [
                    {
                        "@type": "Provenance",
                       ...
                    }
            ],
        },


    <extraction for "Entity-ENG_NW_56055_WMMITREHACK6_0-659-1">
        "states": [
            {
                "@type": "@State",
                "type": "Count",
                "text": "1,418 refugees arrive daily",
                "value": {
                    "@id": "Count-123",
                }
            },
        ]
    ]
```

**Comment by kwalcock** [comment]
That sounds OK.  I would just need to change one of the tables above.  This way it's more in line with the other values anyway.

|<a id="StateType">State type</a>|<a id="ValueType">Value type</a>|Notes|
|---|---|---|
|INC||Indicates that the Concept has been increased.|
|TIMEX|{@id(TimeExpression)}|This is an ID referring to a time expression.|
|<b>COUNT</b>|<b>{@id(Count)}</b>|<b>This is an ID referring to a count.</b>|

**Comment by kwalcock** [comment]
This information has been added to https://github.com/clulab/eidos/wiki/JSON-LD.  @MihaiSurdeanu, a migration event has a timeStart, timeEnd, and time.  What is this last time for?  Also, we don't have much Provenance for COUNT.  Should it get a startOffset, endOffset, and text like the TimeExpresson and GeoLocation have?  The text is already in the code, but offsets are not yet available.

**Comment by MihaiSurdeanu** [comment]
@zupon, @maxaalexeeva: please confirm that what I say is correct. The only field that really matters between this is `time`. `timeStart` and `timeEnd` are intermediate extractions that are meant to be merged into `time`.

**Comment by zupon** [comment]
That looks correct to me. Ultimately we only want `time` as a time interval, but we can use `timeStart` and `timeEnd` to help us construct that interval, especially if the text only mentions one or the other.

@maxaalexeeva does that sound right to you too?

**Comment by maxaalexeeva** [comment]
Yes. There might be two different `time`s, I guess: the one that can be found by the rule directly (@kwalcock, that time arg you asked about in your message) and the one we will construct from timeStart and timeEnd using an action---both will be intervals, but we will be getting at them in different ways (rule vs. action)

**Comment by kwalcock** [comment]
I'm wondering whether in the end all three of the times will really be exported to JSON-LD.  I can wait and see.  If they aren't, then they can't be read back in, either, and that means there would need to be a representation that doesn't include anything extra.  However, first things first.

I also hope that Steve's work is not going to affect the immigration events, or affects them in a good way.  Times are very soon to be included as Mentions and perhaps they are more accessible to you that way.  I assume Mihai or Becky is keeping an eye on that.

**Comment by maxaalexeeva** [comment]
> I also hope that Steve's work is not going to affect the immigration events, or affects them in a good way. 

@kwalcock, I am trying to merge Steve's code from master into a copy of our migration branch to see if they work well together (to address what you discuss in issue https://github.com/clulab/eidos/issues/614). There are a few conflicts I am not sure how to resolve between the branches, so I might open a separate issue to check in with everyone involved.

**Comment by MihaiSurdeanu** [comment]
Ideally, we should only export the `time` field. However, we currently do not merge `timeStart` and `timeEnd`, because we were waiting for Steve's changes to temporal mentions.

**Comment by kwalcock** [comment]
We're not even using migration anymore.
