### ISSUE TITLE
Possible infinite loop in timenorm code

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#631]
There are about 10 files in a recent batch where the timenorm code seems to hang.  In any case, some fairly small files are taking a very, very long time to process.  One is attached.  In TimeNormFinder, the call to
```
parser.intervals(parsed.tail, eidosDocument.dct.map(_.interval))
```
at line 108 does not return.  TemporalNeuralParser.intervals is synchronized, so all other threads have to wait even if their files are not problematic.  This wreaks havoc on the batch, of course :(.  

I hope that some timenorm experts will be able to look at it and easily recognize what is going awry.

[Global20Weather20Hazard161201.txt](https://github.com/clulab/eidos/files/3418793/Global20Weather20Hazard161201.txt)

**Comment by EgoLaparra** [comment]
This will change and probably be solved along with https://github.com/clulab/eidos/issues/630

**Comment by kwalcock** [comment]
Indeed, the problem has disappeared!
