### ISSUE TITLE
Turn on geo/time extractions in Dockerfile

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#638]
Currently `useTimeNorm` and `useGeoNorm` are set to `false` by default in `reference.conf`, and this change propagates into the dockerized version of Eidos. Would it make sense to set these to `true` in the Dockerfile? Are there any other steps needed to make geo/time extractions work other than changing the config file?

**Comment by kwalcock** [comment]
I should remove those from reference.conf.  They are no longer used by Eidos.  Instead, Eidos checks the list of entityFinders, first in eidos.conf and only if needed in reference.conf.  If it sees "geonorm" or "timenorm" in the list, then it uses them.  Does that coincide with the behavior that you are observing?  This part of Eidos has changed quite a bit recently.

**Comment by bgyori** [comment]
Got it, that wasn't clear to me! Yes, then removing them from reference.conf should be fine.

**Comment by bgyori** [comment]
Resolved by #641
