### ISSUE TITLE
DocumentFilter changes the text permanently

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#652]
I've been comparing eidos output of text documents that have been converted from PDF by various programs and with and without addition of periods.  In trying to match up text files with the jsonld output I notice that Eidos itself is changing the text.  It's not only the period adding program that is an issue.  DocumentFilter is playing with whitespace, which is a relatively safe thing to do, but it seems like a problem waiting to happen.  I suspect that the text can be changed back after the annotation is complete so that any output of the program will match the input text.  I'm going to test whether this is the case.  I think there might also be a chance here for more complicated filters that work on periods and want to experiment with that.  It seems like there is something relatively transparent that could be slipped in here that might save us a lot of grief.

**Comment by MihaiSurdeanu** [comment]
Can you please give a simple example for this?

**Comment by kwalcock** [comment]
Do you mean something like

before: `April1 2017\n\nHIGHLIGHTS  In February 2017, overall inflation and food inflation rates in South Sudan stood at 425.9 percent and at 480.5 percent respectively.`

after: `April1 2017  HIGHLIGHTS  In February 2017, overall inflation and food inflation rates in South Sudan stood at 425.9 percent and at 480.5 percent respectively.`

or

before: `SOUTH SUDAN MONTHLY MARKET PRICE MONITORING.\n\nApril1  2017.\n\nHIGHLIGHTS.\n\n`

after: `SOUTH SUDAN MONTHLY MARKET PRICE MONITORING.\n April1  2017.\n HIGHLIGHTS.\n `

**Comment by kwalcock** [comment]
This has been addressed with #653.

**Comment by MihaiSurdeanu** [comment]
Thanks!

This is fairly easy to recover though, because we keep track of the character offsets, no?
I'll take a look at the PR soon.

**Comment by kwalcock** [comment]
The whitespace changes aren't recoverable solely from a Document object as far as I know.  For sentences we have copies of both the raw and processed character strings for the words, but there is no backup copy of anything between the words.  The PR fills the spaces back in.
