### ISSUE TITLE
Negative time intervals

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#665]
We found that in the latest output, several "negative" time intervals are reported in TimeExpressions. For instance, 

```
113943       "timexes" : [ {
113944         "@type" : "TimeExpression",
113945         "@id" : "_:TimeExpression_80",
113946         "startOffset" : 31959,
113947         "endOffset" : 31983,
113948         "text" : "November-to-January 2013",
113949         "intervals" : [ {
113950           "@type" : "TimeInterval",
113951           "@id" : "_:TimeInterval_53",
113952           "start" : "2013-01-01T00:00",
113953           "end" : "0014-12-01T00:00"
113954         } ]
```
in `17873e4eddc4aa7bcd5146b814ce1f42.jsonld` (@kwalcock should have a copy of this file) the end time stamp is before the start time stamp. 

Another example is 

```
227492       "timexes" : [ {
227493         "@type" : "TimeExpression",
227494         "@id" : "_:TimeExpression_190",
227495         "startOffset" : 64378,
227496         "endOffset" : 64392,
227497         "text" : "until November",
227498         "intervals" : [ {
227499           "@type" : "TimeInterval",
227500           "@id" : "_:TimeInterval_134",
227501           "start" : "2014-11-01T00:00",
227502           "end" : "2014-10-02T00:00"
227503         } ]
```
from the same file. 

Question is, are these considered bugs in time expression extraction, and should be fixed at the reader level, or should we take them as is, and handle them downstream?

**Comment by kwalcock** [comment]
Thanks for the sharp eyes.  Our time gurus have been assigned.

**Comment by EgoLaparra** [comment]
Can you share the text file, please?

**Comment by kwalcock** [comment]
Here you go.

[17873e4eddc4aa7bcd5146b814ce1f42.txt](https://github.com/clulab/eidos/files/3593026/17873e4eddc4aa7bcd5146b814ce1f42.txt)

[17873e4eddc4aa7bcd5146b814ce1f42.jsonld.txt](https://github.com/clulab/eidos/files/3593035/17873e4eddc4aa7bcd5146b814ce1f42.jsonld.txt)

[17873e4eddc4aa7bcd5146b814ce1f42.json.txt](https://github.com/clulab/eidos/files/3593029/17873e4eddc4aa7bcd5146b814ce1f42.json.txt)

**Comment by bethard** [comment]
I'm guessing that these both parse as a `Between`, and we mis-parse one of the endpoints. @EgoLaparra: Can you check if that's the case, and if so, maybe `Between.isDefined` should have an additional check that if both `startInterval` and `endInterval` are defined, it is also the case that `startInterval` ends before `endInterval`. That way, the above examples would result in `isDefined = false` and would not show up in the Eidos output.

**Comment by EgoLaparra** [comment]
@bethard, your guess was correct. I've opened a new pull request in the timenorm repo.
