### ISSUE TITLE
Host not allowed when running Dockerized web service

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#666]
With the "old" Dockerfile, built ~7 months ago, before the recent additional Dockerfiles were developed, the way I was able to set up a public facing (i.e., not just called from localhost) Eidos web service was by adding
```
play.filters.hosts {
  allowed = ["<public IP of server>:9000"]
}
```
to webapp/conf/application.conf. Without this change, the web server prints
```
[warn] p.f.h.AllowedHostsFilter - Host not allowed: <public IP of web server>:9000
```
and the caller gets a "bad request" error. With the change to webapp/conf/application.conf, remote requests work fine.

I have tried setting up a web service based on the latest DockerfileRunProd. The service works well when called from localhost. But it gives the same error as above for remote requests. I tried modifying webapp/conf/application.conf as above but in this setting, it did not seem to have any effect. What would be the right way to enable remote requests when using DockerfileRunProd?

**Comment by kwalcock** [comment]
I'm not sure why it wouldn't work the same way, but will try to replicate it.  Did I miss that play.filters.hosts addition in the Docker file somewhere?

**Comment by kwalcock** [comment]
If you are wanting to get the same results as the batch that just ran, I should merge the outstanding PR.

**Comment by bgyori** [comment]
The play.filters.hosts setting is something I added to the Docker image after the Dockerfile setup. The difficulty in automating that is that <public IP of server> has to be the actual IP of the server. I wonder, though, if setting 0.0.0.0 would work, or if there is some other setting that just universally allows remote requests on port 9000 that could then be added to the automated Docker build.

No need to rust the outstanding PR, this is sort of independent of that.

**Comment by kwalcock** [comment]
Running Eidos inside a virtual machine, but not yet a Docker file in addition, and using both run and runProd, I got the same results either way.  Without the change to application.conf, only localhost:9000 worked and with the change, only http://10.0.2.15:9000/ worked.  Could it be that the change to application.conf is not happening at the right time during the construction of the docker image?

Are you able to run Eidos webapp directly, not containerized and connect?  The commands would be

```
$ sbt
sbt:eidos> project webapp
[webapp] $ runProd
```

**Comment by kwalcock** [comment]
```
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
```
At https://www.playframework.com/documentation/2.7.x/AllowedHostsFilter there is mention of `anyhost`.  Also a plain period might work:
```
    # A list of valid hosts (e.g. "example.com") or suffixes of valid hosts (e.g. ".example.com")
    # Note that ".example.com" will match example.com and any subdomain of example.com, with or without a trailing dot.
    # "." matches all domains, and "" matches an empty or nonexistent host.
    allowed = ["localhost", ".local", "127.0.0.1"]
```

**Comment by bgyori** [comment]
Thanks, will try these soon!

**Comment by bgyori** [comment]
This works now, I actually made a mistake in setting up the hosts filter, otherwise 
```
play.filters.hosts {
  allowed = ["<public IP of server>:9000"]
}
``` works as expected. No need to fix anything!

**Comment by bgyori** [comment]
Actually, it might make sense to add a default filter to application.conf in the Dockerfiles, I'll submit a PR.

**Comment by kwalcock** [comment]
Sounds good.
