### ISSUE TITLE
Compositional Grounding API

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#671]
This is where we can discuss this topic.

**Comment by kwalcock** [comment]
@BeckySharp, I made a first draft of the grounding as a post-processing stage with an optional var containing the result as we discusses just over a week ago.  I have not yet moved the canonical name into the grounding, but given the additional grounding algorithm which will have its own data, that seems to be the right thing to do.  I'll check that nothing else uses it and head in that direction.

**Comment by MihaiSurdeanu** [comment]
@bgyori: this is so we can discuss the reader API for the compositional grounding.

What we had in mind:
- We do NOT remove anything from the current output, so we maintain backwards compatibility (for better or worse). 
- For concepts that include a core concept + a property/process/phenomenon in the same phrase, we include information from compositional grounding. In particular, this will include:
1. The core concept in the phrase. For example, in the phrase "price of oil", the core concept is "oil". This core concept will be associated with top K possible groundings.
2. A list of 1 or more modifiers, where a modifier will be a property/process/phenomenon. For example, for the phrase "price of oil", the modifiers will be: Modifiers(Property("price")). Same as above, each modifier will be associated with top K groundings.

@bgyori: does this sound Ok to you?
@kwalcock: can you please think of the data structure to represent this internally?
@BeckySharp: can you please implement the internal call to the compositional grounding algorithm to produce this data?
@zupon: can you please implement the above using the syn+sem heuristics we discussed today?

Thank you all!

**Comment by bgyori** [comment]
Yes, that sounds good to me!

**Comment by BeckySharp** [comment]
Small note:
I think that the above "price of oil" would actually be:  Modifiers(Property("price"), Phenomenon("oil")) and theoretically you can use the "Modifiers" flavor of grounding in place of the original (assuming you have an algorithm for it)

**Comment by MihaiSurdeanu** [comment]
Good catch.

**Comment by kwalcock** [comment]
@BeckySharp, in your example is the CoreConcept still "oil" in addition to the Phenomenon being "oil"?  It looks like I will also have to remember whether something is a property, process, or phenomenon.  The slashes weren't just a way to describe some vague P-thing, but the specific P is valuable information?

**Comment by kwalcock** [comment]
The scaffolding is in branch kwalcock-reground.  I'm removing the pull request that demos it so that it doesn't accidentally get merged into main.

**Comment by BeckySharp** [comment]
sounds great!
