### ISSUE TITLE
Error in eidos_reader

### ISSUE THREAD

**Issue by phosseini** [clulab/eidos#672]
Such an error is [reported before](https://github.com/clulab/eidos/issues/552), but I still have no idea what causes such an error.

I'm simply running the example below from the documentation:

```
from indra.sources import eidos
ep = eidos.process_text("Water trucking has decreased due to the cost of fuel.")
```
And I get the following error:

```
jnius/jnius_export_class.pxi in jnius.JavaClass.__init__()

jnius/jnius_export_class.pxi in jnius.JavaClass.call_constructor()

jnius/jnius_conversion.pxi in jnius.populate_args()

jnius/jnius_utils.pxi in jnius.check_assignable_from()

JavaException: Invalid instance of 'java/lang/Object' passed for a 'org/clulab/wm/eidos/EidosComponents'
```

I followed all the instructions and I have no problem using other classes from INDRA, I think this is just Eidos related. Any idea?

**Comment by bgyori** [comment]
Hi @phosseini, I'm pretty sure that this has to do with your versions of Eidos and INDRA being out of sync. Try to make sure that you have the latest Eidos packaged as a JAR, and INDRA installed from Github (i.e., pip install git+https://github.com/sorgerlab/indra.git).

Having said that, an alternative way of using Eidos via INDRA is as a web service. You can follow the README instructions on running and Eidos webapp, and then do something like:
```
from indra.sources import eidos
eidos.process_text(text, webservice=<address of local Eidos web service>)
```
This avoids code-level dependencies between the two systems.

**Comment by kwalcock** [comment]
The mention of EidosComponents makes me think that there's a mismatch in the call to the EidosSystem constructor, which was recently changed.  I think this has been tested, though.  Something calling the old `def this(x: Object) = this()` might do it, so I think that Ben is probably correct.

```scala
class EidosSystem(val components: EidosComponents) {
  // The constructor below will take cheap to update values from the config, but expensive
  // values from eidosSystem.components, if present  It is the new reload().
  def this(config: Config, eidosSystemOpt: Option[EidosSystem] = None) =
      this(new EidosComponentsBuilder().add(config, eidosSystemOpt.map(_.components)).build())
  def this() = this(EidosSystem.defaultConfig)
  // Python now uses the default, empty constructor above, but the line below remains for documentation purposes.
  // def this(x: Object) = this() // Dummy constructor crucial for Python integration
```

**Comment by phosseini** [comment]
> Hi @phosseini, I'm pretty sure that this has to do with your versions of Eidos and INDRA being out of sync. Try to make sure that you have the latest Eidos packaged as a JAR, and INDRA installed from Github (i.e., pip install git+https://github.com/sorgerlab/indra.git).
> 
> Having said that, an alternative way of using Eidos via INDRA is as a web service. You can follow the README instructions on running an Eidos webapp, and then do something like:
> 
> ```python
> from indra.sources import eidos
> eidos.process_text(text, webservice=<address of local Eidos web service>)
> ```
> 
> This avoids code-level dependencies between the two systems.

Thanks, I could run the example by adding the `webservice` parameter. I'm pretty sure I'm using the latest version of INDRA (`indra==1.13.0`) and EIDOS but I'll go and check it again. The only problem now is that I get the very error when I'm using delphi which is built upon INDRA and EIDOS. Running the example below I get that error:

```
from delphi.AnalysisGraph import AnalysisGraph
G = AnalysisGraph.from_text(
    "Significantly increased conflict seen in South Sudan forced many"
    " families to flee in 2017.")
G.map_concepts_to_indicators()
G.parameterize(country="South Sudan", year=2017, month=4)
A = G.to_agraph()
A.draw("CAG.png", prog="dot")
```

I wonder if you have any idea if I can use the Eidos's local server for delphi as well?

**Comment by phosseini** [comment]
I could also run delphi using Eidos's `webservice` local web service (such a useful parameter!) Thanks for all the help.

**Comment by bgyori** [comment]
Okay, great! INDRA's official PyPI release (in this case 1.13.0) lags behind the latest code on Github so it makes sense to pip install it from Github directly. In any case, using the webservice-based integration is more convenient in many ways.
