### ISSUE TITLE
sbt assembly errors

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#692]
On the latest master, when I attempt to run `sbt assembly` (the standard method to produce a protable JAR file of Eidos), I get an error:
```
...
[info] Done compiling.
[path to eidos]/build.sbt:186: error: not found: value assembly
test in assembly := {}
        ^
[error] Type error in expression
```
I tried to look into what changed to cause this error, and found that f6d2717238d80eb52cf00b3b3b40a0dc9591edf1 still worked, whereas fd5e35c9c3bc72e3aa6c819f0ee894c7ca73b4dd was broken. While I don't fully understand the changes in that commit, one potentially relevant addition is this line to project/assembly.sbt
```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")
```

**Comment by kwalcock** [comment]
There is an sbt-assembly added in package/plugins.sbt and another in package/assembly.sbt.  I think it will work if one or the other is removed.  I'll have to track down the details, though.

**Comment by kwalcock** [comment]
#693 should take care of this.  Note that we missed some filename changes in the Docker and configuration files.

**Comment by bgyori** [comment]
Thanks, that worked!
