### ISSUE TITLE
Grounding to only leaf nodes in the ontology

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#697]
I wanted to raise this issue for discussion: Eidos currently only grounds to the leaf nodes of the YAML ontology (e.g., wm.yml) that it is provided. Whether or not this yields good results certainly depends on the specifics of the ontology, but my feeling is that for the WM ontology specifically, this can produce suboptimal results. Consider, for instance, the sentence, "conflict causes a decrease in living conditions". Both `conflict` and `living_conditions` are in the ontology, but they both subsume a number of more specific leaf concepts like `unsanitary_condition` under `living_condition`. This results in any mention of "living condition" to be grounded to the more specific `unsanitary_condition`. If there is no technical barrier to grounding to non-leaf entries, I think it would generally improve the results by allowing the system to capture the level of detail at which concepts are described in text more faithfully. Any thoughts?

**Comment by BeckySharp** [comment]
@kwalcock has this been merged in yet, with the compositional grounding? or is it next?

**Comment by kwalcock** [comment]
No, it is not in master yet.  It may be next.  The main problem is that it messes up the compact tree representation which means that the cache doesn't work.  It has also not been adequately studied, IMO.  I'm hoping that this test data that Mihai sent recently can be used to conclusively say that the parents are needed (and that they don't need examples, descriptions, patterns, parsing, themselves).

**Comment by bgyori** [comment]
This has since been fixed so I'm closing the issue.
