### ISSUE TITLE
newly-found geolocs breaking tests (but maybe in a good way)

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/eidos#699]
Hi @BeckySharp,

By finding geolocations, we have broken 4 other tests, e.g., this one:
https://github.com/clulab/eidos/blob/6684cf393c025572abaa30327e2f2c1aac402948/src/test/scala/org/clulab/wm/eidos/text/english/cag/TestCagP3.scala#L54

The newly-found geoloc in this example attaches to the insecurity node, which is not part of the test:

![Screenshot from 2019-10-24 10-26-33](https://user-images.githubusercontent.com/31713912/67510042-1cef4880-f649-11e9-8d7d-ba23f34f3533.png)

How would you like to proceed with tests like this? Would you be fine ignoring them for the time being? Or would you want the geoloc attachment to be added to the test? (I am in favor of the second option; the  location attachment seems to make sense there in a similar way to the time attachment)

**Comment by BeckySharp** [comment]
We should add it to the test!

**Comment by BeckySharp** [comment]
was this resolved with #700?

**Comment by maxaalexeeva** [comment]
Yes. Sorry.

**Comment by BeckySharp** [comment]
thanks, and don’t be! I was just seeing what could be closed! :)
