### ISSUE TITLE
Some tests aren't testing

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#708]
Some tests are missing their `should be(successful)` so that they really aren't checking the result of the test.  Lots of them are failing and we don't know it.

**Comment by BeckySharp** [comment]
thanks for finding this -- working on them now!

**Comment by kwalcock** [comment]
I see that at one time there were lots of them missing in TestDoc1.scala.

**Comment by BeckySharp** [comment]
yes, and in testdoc4 etc :)
