### ISSUE TITLE
Regrounding with new ontology errors

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#717]
When calling `EidosSystem.components().ontologyHandler().reground()` with the content of 
https://raw.githubusercontent.com/WorldModelers/Ontologies/master/wm_with_flattened_interventions_metadata.yml, I get the following error: `java.lang.Integer cannot be cast to java.util.Collection`. When doing the same with https://raw.githubusercontent.com/WorldModelers/Ontologies/master/wm_metadata.yml, the same method works. I couldn't immediately figure out why the error happens but maybe the ontology file uses an unexpected formatting for some entries? For context, I'm using the latest master as a JAR file via Python.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: can you please take a look?

**Comment by kwalcock** [comment]
Yes, I'm looking.  The file doesn't get tested either by WorldModelers/Ontologies or clulab/eidos, so there's probably some oddity.

**Comment by kwalcock** [comment]
So far I haven't had any luck reproducing.  Can you give any further hints, such as the arguments that you are passing or some line number from an exception?  Here's my experiment:

```
# First turn on useW2V in eidos.conf
> cd eidos
> sbt
sbt:eidos> console
scala> import org.clulab.wm.eidos.EidosSystem
scala> import org.clulab.wm.eidos.utils.FileUtils
scala> val reader = new EidosSystem()
scala> val ontologyHandler = reader.components.ontologyHandler
scala> val yaml = FileUtils.getTextFromFile("./wm_with_flattened_interventions_metadata.yml")
scala> val result = ontologyHandler.reground("keith", yaml, Seq("This is one text", "This is another"), true, 10)
```

**Comment by BeckySharp** [comment]
any luck on this?

**Comment by bgyori** [comment]
I'm still trying to figure it out, will post here once resolved.

**Comment by bgyori** [comment]
The issue was a misplaced polarity entry in the ontology. It only made a difference if the YAML was deserialized and then serialized again, which is why it couldn't be reproduced above. Overall, nothing needs to be done in Eidos!

**Comment by kwalcock** [comment]
Thank you!  That's a relief.  I was at a loss for an explanation.  It sounds like the file must have changed after some round trip through serialization.
