### ISSUE TITLE
webapp brat syntax display broken 

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#735]
The syntax brat on the webapp is no longer displaying (on master).
Did we recently update something?  I looked through the "blame" on github and can't find any recent changes to HomeController or index.scala.html that would have done it... :(

@kwalcock can you please help!? :(

**Comment by kwalcock** [comment]
Looking now

**Comment by kwalcock** [comment]
Can you give an example?  My one test gives this output.  Is something missing?

![brattop](https://user-images.githubusercontent.com/8679738/72672377-2b65ba00-3a16-11ea-98cd-794ca6031863.png)

![bratbot](https://user-images.githubusercontent.com/8679738/72672380-37517c00-3a16-11ea-897d-379a6c95d93b.png)

**Comment by BeckySharp** [comment]
it's a Martin Luther King Day miracle!
I was getting an empty blue outline box thing instead of the display... i tried switching branches etc and it was there.  But now, it's working again? though I changed nothing? 
I'd think it was a browser caching thing, but I even tried in chrome....
ok -- well, then either a tesseract or a miracle or just some weird user error... 
THANKS!
