### ISSUE TITLE
'not been possible' is not recognized as decrease trigger 'inhibit'

### ISSUE THREAD

**Issue by Fan-Luo** [clulab/eidos#74]
Sentence p4s4 in testCAGP4.scala:

> Borehole repairs have not been possible in areas hardest hit by conflict, including large swathes of Upper Nile, due to lack of access due to insecurity and lack of technical expertise and supplies.

It is supposed to capture entity "Borehole repairs" with decrease trigger 'inhibit', but 'inhibit' itself does not appear in the sentence.

> val repairs    = newNodeSpec("Borehole repairs", newDecrease("inhibit"))

**Comment by bsharpataz** [comment]
just pick up for now as Decrease
