### ISSUE TITLE
Request to update path for vectors.txt

### ISSUE THREAD

**Issue by ishu59** [clulab/eidos#743]
I am trying to download vectors.txt from path given in the document but the file is no longer available on the google drive. Please update the path to this file

**Comment by kwalcock** [comment]
Thanks for spotting that.  I'm not sure where they went, but I am uploading new copies now.

**Comment by kwalcock** [comment]
The link to vectors should be fixed.  Glove is still uploading.

**Comment by kwalcock** [comment]
It seems to work, so I'm closing the issue now.
