### ISSUE TITLE
Add ground_texts endpoint to webapp

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#747]
For integration with various workflows, it would be really useful to expose the reground method (https://github.com/clulab/eidos/blob/45dbf5fffb6b58659644c543ec1142a641184d8b/src/main/scala/org/clulab/wm/eidos/groundings/OntologyHandler.scala#L41) as a webapp endpoint. The endpoint could have the same interface as the method, where the caller provides a YAML ontology string, a list of entity text strings to ground, and some further parameters (name, filter, topk, isAlreadyCanonicalized). The availability of such an endpoint would streamline assembly workflows which currently need to load Eidos as a JAR for regrounding.

**Comment by kwalcock** [comment]
Noted.  I can probably get to it within a few days if everyone else approves.  Do you just need the interface, not a form?

**Comment by bgyori** [comment]
Yes, just the interface for programmatic use, I wouldn't be using a web form. Thanks!

**Comment by kwalcock** [comment]
I'm working on this now.  Does it need to work in a particular older branch or release for sake of compatibility?

**Comment by bgyori** [comment]
Done in #748
