### ISSUE TITLE
change argument names

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#75]
- to more generic names (i.e., src/target, controller/controlled, whichever)
- check to make sure other code doesn't break in webapp/brat vis, etc
- coord with @kwalcock to make names work with JSON-LD reps

**Comment by bsharpataz** [comment]
DirectedRelations may well stick with causal, so `cause` and `effect` are likely fine for now.  Correlation was moved to UndirectedRelation

todo: do we still need to change args?

**Comment by kwalcock** [comment]
In the JSONLD we have sources and destinations as generic terms.  It seems like one can only only conclude that these are cause and effect by noticing that the rule which produced them is a causal rule.  We're getting more rule types and other groups will need to know the role of the source and destination without having to decipher a rule.
