### ISSUE TITLE
Adjective grounding needs to be added to the pipeline

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#783]
At one time and for various reasons the design had no vars for an EidosMention.  This was recently changed so that the canonicalName and groundings are vars.  I realize now that there is one more dangling piece of data: the adjective groundings.  These are being added optionally just for the jsonld export and they're the reason that in lots of apps there is this strange adjectiveGrounder being constructed in order to do the serialization.  It's quite a distraction.  IMO the adjective grounding should be added to the main pipeline.  If necessary, it could be turned off by default via the options.  This means that the serializer doesn't need to know anything about the grounding.  The deserializer can be made to read it back in if present.  The information is otherwise lost and we've been reconstituting on round trips.  The adjective grounder would become part of the EidosComponents and potentially accessible there for anything that still needs its own.  It would even be guaranteed to be the same one that the reader used.  Ensuring that was previously reason for excessive handling of config variables.

**Comment by bgyori** [comment]
Done in #748

**Comment by bgyori** [comment]
Oh no, so

**Comment by kwalcock** [comment]
#791 addresses this issue.
