### ISSUE TITLE
Sentence splitting

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#789]
This is seen by processors as one sentence, is it something we can address with the sentence splitter or something?

`An increase in assessed settlements reported access to functional boreholes in November , which can be attributed to the scaling up of humanitarian activities from the WASH cluster to rehabilitate boreholes in Jur River and Wau Counties.17 The overall percentage of functional b`oreholes increased across WBeG , specifically in Jur River and Wau Counties in November .`

**Comment by MihaiSurdeanu** [comment]
I'll look at this.

**Comment by MihaiSurdeanu** [comment]
Fixed in processors PR #370. There is even a unit test for this text :)
