### ISSUE TITLE
P4S2 in TestCagP2.scala

### ISSUE THREAD

**Issue by Fan-Luo** [clulab/eidos#82]
Sentence:

    Violence has caused livestock to be looted, killed and disease-prone and crops destroyed, and displacement has caused delayed planting.

Test:
    
    tester.test(newEdgeSpec(displacement, Causal, delayedPlanting)) should be (successful)
    
Problem: 
    
    delayedPlanting is not extracted, as shown in figure below.
 ![](https://i.imgur.com/O55ObXj.jpg)

I tried to debug and noticed that both  ‘delayed’ and ‘planting’ are considered as I-VP
 ![](https://i.imgur.com/FwjazQ4.jpg)

The tag for 'delayed planting’ also seems wrong:
    ‘delayed’ is considered as VBN, and ‘planting’ is considered as VBG.
 ![](https://i.imgur.com/aPnl6Y0.jpg)

This issue seems from tagPartsOfSpeech in processor.

**Comment by MihaiSurdeanu** [comment]
I think we should give up on this. That is, change delayed planting to another NP that is correctly recognized.
