### ISSUE TITLE
Deduplication error during assembly

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#823]
I am getting a deduplication error with the latest master when running `sbt assembly`:
```
[error] (assembly) deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/javax.xml.bind/jaxb-api/jars/jaxb-api-2.4.0-b180830.0359.jar:module-info.class
[error] /home/bmg16/.ivy2/cache/com.sun.xml.bind/jaxb-impl/jars/jaxb-impl-2.4.0-b180830.0438.jar:module-info.class
```
Any thoughts?

**Comment by kwalcock** [comment]
We just solved this in some other related project, reach apparently (https://github.com/clulab/reach/pull/669/commits/69d6648c03c75dc4f1327c42a308176a5edd745b).  I'll need to add these lines for eidos and perhaps for other transitive dependencies of processors.

**Comment by bgyori** [comment]
It works now, thanks!
