### ISSUE TITLE
Error when serializing JSON-LD with SUtime on

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#832]
When reading a batch of documents with the 
```
useNeuralParser = false
```
setting, the system crashed with this error
```
Exception in thread "main" java.lang.Exception: Cannot make reference to unknown identity: TimEx(Interval(2662, 2666),List(TimeStep(2011-01-01T00:00,2012-01-01T00:00)),2011)
	at org.clulab.wm.eidos.serialization.json.JLDSerializer.$anonfun$mkRef$1(JLDSerializer.scala:140)
```
Unfortunately, it is not clear from the logs which document or text specifically caused this. If it's not possible to identify the issue without more specifics, let me know and I'll share the dump of documents.

**Comment by kwalcock** [comment]
@bgyori, you sure are keeping us honest here.  This must be a fairly recent version of Eidos you are using.  Is it recent enough that it has a libraryDependencies like
```
  val      procVer = "8.0.1"
```
but not yet
```
  val      procVer = "8.0.3-SNAPSHOT"
```
If so, then the problem *might* well be related to a processors bug that has been fixed but not yet published in version 8.0.3.  At least a very similar error went away after that change.  Maybe @MihaiSurdeanu can weigh in about a processors update.

**Comment by bgyori** [comment]
Yes, I just pulled the latest master today and worked with that, I promise I'm not trying to break the system on purpose :)

**Comment by MihaiSurdeanu** [comment]
Should I release 8.0.3?

**Comment by kwalcock** [comment]
The fix held up through the rest of the 8311 documents and it looks like there is a customer already.  I just don't know about the other changes, especially those on the verge of being added.

**Comment by kwalcock** [comment]
Processors has been updated to 8.0.3 and the master branch of Eidos now uses it.  I'll close this until another error is encountered.

**Comment by bgyori** [comment]
Thanks!
