### ISSUE TITLE
Add SRL functionality to Eidos

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/eidos#894]
Processors 8.1.3 has been released and should be available on maven in a couple of hours. It adds FastNLPProcessorWithSemanticRoles, which does what the name says.
See a simple example here:
https://github.com/clulab/processors/blob/master/corenlp/src/test/scala/org/clulab/processors/TestFastNLPProcessor.scala#L96

To play with it, type "./shell" in the processors repo, and select the "fast" processor.

@kwalcock: can you please replace the FastNLPProcessor in Eidos with this new one? Existing functionality should be identical, so no unit tests should be broken by this change...

FYI @BeckySharp.

**Comment by kwalcock** [comment]
Does someone need to have this released/published?

**Comment by MihaiSurdeanu** [comment]
If by *this*, you mean processors, it has been released.

**Comment by kwalcock** [comment]
No, I mean the corresponding changes in Eidos.  Do they need to be released or is being in master sufficient?

**Comment by MihaiSurdeanu** [comment]
Master is Ok.
