### ISSUE TITLE
SRLCompositionalGrounder crashes

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#907]
In outgoingOfType(), the tok value is sometimes greater than dependencies.outgoingEdges can handle and an exception is thrown.  If the code
```scala
    if (tok >= dependencies.outgoingEdges.length)
      println("Something is very wrong!")
```
is added, one can catch it before it happens and inspect.  4 of 52 test files including the one attached seem to cause the problem.  The size of outgoingEdges in one case is 24.  The tokenInterval is 2-24 and it is the 24th that causes the problem.

[3_ALPAN_Paper_10.txt](https://github.com/clulab/eidos/files/5309062/3_ALPAN_Paper_10.txt)

**Comment by MihaiSurdeanu** [comment]
Can you please point me to the class where it happens?

**Comment by kwalcock** [comment]
I didn't check for multiple classes in the file.  It's in SentenceHelper in SRLCompositionalGrounder.scala.

**Comment by kwalcock** [comment]
https://github.com/clulab/eidos/blob/6ebd4b3a674294d7ca24073197c614e119c66965/src/main/scala/org/clulab/wm/eidos/groundings/grounders/SRLCompositionalGrounder.scala#L426

**Comment by BeckySharp** [comment]
the dependencies array isn't shorter like the srl one, right @MihaiSurdeanu ?

**Comment by MihaiSurdeanu** [comment]
It should not be. Is `dependencies` the syntax ones or SRL here?

**Comment by MihaiSurdeanu** [comment]
Also, if this is causing so much pain, should I enforce the SRL ones to be the size of the sentence?

**Comment by kwalcock** [comment]
BTW, thanks @BeckySharp for so cleanly adding things like IndividualGrounding to the messy OntologyGrounder.scala code.  The JSONLD deserialization is ready and the present issue was only found while I was giving the serialization a good workout.

**Comment by BeckySharp** [comment]
OK, i can check when i get back if this isn't solved yet -- and no, Mihai,
these are the syntax deps, not the SRLs, so no changes are needed there

**Comment by BeckySharp** [comment]
though fwiw you may want to add a helper method to return Array.empty when
someone tries to `get` the outgoing for a SRL beyond the array...?
they could all point to the same Array.empty

**Comment by MihaiSurdeanu** [comment]
FYI: a bug fix for this has been merged in master in processors. We now guarantee that semantic deps have the same size as the sentence.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: can you please test if this bug happens with the latest processors? If not, maybe we should merge the parallel branch too, and then release 8.2.2?

**Comment by kwalcock** [comment]
Yes, the testing was my plan exactly.

**Comment by kwalcock** [comment]
It may be that I am being deceived, but it doesn't seem to have worked.  I see things like words = String[30] and dependencies.outgoingEdges = Tuple2[29] and preferredSize = None.  The processor in question is a FastNLPProcessorWithSemanticRoles and it appears that the DirectedGraphs are initialized along a different route than what was changed.  They come from FastNLPProcessor.parseWithStanford which calls CoreNLPUtils.toDirectedGraph(basicDeps, in) which makes a DirectedGraph without the preferredSize.  In IntelliJ you can right click on the constructor for DirectedGraph and select "Find Usages".  "New instance creation" is probably the right category to double check.  I'm not sure which all of them are necessary to convert, but at least one is missing the new argument.

**Comment by MihaiSurdeanu** [comment]
Oh, I think I know what's going on. Hang on.

**Comment by BeckySharp** [comment]
also i’m not looking at the code, but i thought i switched to cluprocessor,
right? or am i crazy?

**Comment by MihaiSurdeanu** [comment]
Testing the fix...

**Comment by MihaiSurdeanu** [comment]
Ok, can you please try now?

**Comment by kwalcock** [comment]
I was looking at EidosProcessor rather than the SRLCompositionalGrounder for the processor.  They may be getting tangled up somehow.

**Comment by kwalcock** [comment]
It doesn't look like https://github.com/clulab/processors/pull/426 fixed it.  Although eidos uses two different processors in the task, it seems that CluProcessor somehow causes the problem single handedly.  The computer may still be deceiving me, but I think that @BeckySharp 's observation above is pertinent.

**Comment by MihaiSurdeanu** [comment]
So the crash is in processors on the file attached in this thread ?

**Comment by kwalcock** [comment]
No, it happens in SRICompositionalGrounder.scala in SentenceHelper.outgoingOfType in which tok (tokenIndex?) is off the end of dependencies.outgoingEdges.  How it gets in the situation is the difficult question.  I notice in SentenceHelper that the length of outgoingEdges of srls and dependencies differs.  Dependencies is one shorter somehow.

**Comment by kwalcock** [comment]
Yes on the attached file and three others, though.

**Comment by kwalcock** [comment]
This means size of graphs (outgoingEdges) for ENHANCED_SEMANTIC_ROLES is not the same as for UNIVERSAL_ENHANCED.

**Comment by kwalcock** [comment]
For a CluProcessor.

**Comment by MihaiSurdeanu** [comment]
Thanks! I'll debug this today.

**Comment by MihaiSurdeanu** [comment]
I can't replicate this bug. I wrote a test for this here:
https://github.com/clulab/processors/blob/takethree/main/src/test/scala/org/clulab/processors/TestDepGraphSizes.scala

And it passes for me in this branch...

**Comment by kwalcock** [comment]
This seems to have been solved with https://github.com/clulab/processors/pull/428.
