### ISSUE TITLE
P3S2 in TestCagP3.scala

### ISSUE THREAD

**Issue by EgoLaparra** [clulab/eidos#91]
I have problems with three of the four tests for p3s2. Besides, there seem to be some faulty causal relations.

---

![causalgraph](https://user-images.githubusercontent.com/4419954/36359342-7586225c-14d7-11e8-91cf-74b72cacb81f.png)

![depgraph](https://user-images.githubusercontent.com/4419954/36359340-6cf3aea2-14d7-11e8-823c-d256f7a513d5.png)

---
Test:

     val impacts = NodeSpec("impacts of flooding")
     val insecurity = NodeSpec("food insecurity", Quant("critical"))
     tester.test(EdgeSpec(impacts, Causal, production)) should be (successful)

Problem:

     Error In the dependency graph: "flooding" is a nmod_of of "collapse" instead of "impacts", so they are extracted as separated entities

---
Test:

      val conflict = NodeSpec("conflict")
      val production = NodeSpec("agricultural production", Dec("reduced"))
      tester.test(EdgeSpec(conflict, Causal, production)) should be (successful)

Problem:

     Error In the dependency graph: "spikes in conflict" is a nmod_as of "remained" instead of nsubj of "reduced".

---

Test:

      val production = NodeSpec("agricultural production", Dec("reduced"))
      val insecurity = NodeSpec("food insecurity", Quant("critical"))
      tester.test(EdgeSpec(production, Correlation, insecurity)) should be (successful)

Problem:

     There is not a clear trigger for this case.

**Comment by bsharpataz** [comment]
i’m working on this, according to webapp I have 2 of them fixed, but sbt
test disagrees... but I’m working on it

**Comment by EgoLaparra** [comment]
In the second test, the entity extracted is "spikes in conflict" instead of "conflict". Could it be a reason for the disagreement?
