### ISSUE TITLE
Apparent infinite recursion in SRLCompositionalGrounder

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#913]
In SRLCompositionalGrounder.packagePredicate I have added the line
```scala
    println(s"At location A, attachedProperties length is ${attachedProperties.length}.")
```
at the top and see that for the attached file (without the .txt) and several others that the length appears to grow without bounds.  This is a recursive function that seems to be in an infinite loop.

Code is from the clulab/eidos repo and the kwalcock-dec2020a branch.  I am running ExtractCdrMetaFromDirectory.scala.  Program arguments are something like `../corpora/dec2020/input/bad/extraslow ../corpora/dec2020/output/bad2 ../corpora/dec2020/badtime.txt 1`.

This problem is preventing completion of our reading, so it is quite important.

[83aece7a9678e760a5e17bb1c64b5a23.json.txt](https://github.com/clulab/eidos/files/5440278/83aece7a9678e760a5e17bb1c64b5a23.json.txt)

**Comment by BeckySharp** [comment]
ok, i'll look. is the json here the cdr for the doc that is failing?

**Comment by kwalcock** [comment]
Yes, that's the CDR.

**Comment by kwalcock** [comment]
Was the intention to used this predicatesCovered to prevent revisiting themes?

**Comment by BeckySharp** [comment]
maybe? i just finished a meeting, looking now

**Comment by BeckySharp** [comment]
ok -- getting it started - making a processors snapshot etc.

**Comment by BeckySharp** [comment]
@kwalcock any particular branch i need processors on?

**Comment by kwalcock** [comment]
I forgot about that.  Sorry.  It might not be necessary for these files.  kwalcock-stopBug.

**Comment by BeckySharp** [comment]
OK, i'm adding back in a check with the predicates covered...
but i find the SRL linkage between the two tokens (10 and 13) very very strange.
I wonder if some of this is related to the tokenizer change somehow -- else the SRL did a weirdly bad job on this sentence.... I can try to parse it in isolation too to see what cluprocessor does indep of eidos.

**Comment by BeckySharp** [comment]
nope -- it's the srl labeler:

```
Array((In,0), (that,1), (vein,2), (,,3), (more,4), (recent,5), (definitions,6),
 (clearly,7), (differentiate,8), (food,9), (security,10), (and,11), (nutrition,12), 
(security,13), (;,14), (for,15), (example,16), (,,17), (a,18), (report,19), 
(by,20), (FAO,21), (,,22), (IFAD,23), (,,24), (and,25), (WFP,26), ((,27), 
(2013,28), (),29), (uses,30), (the,31), (following,32), (definitions,33), 
(:.,34))

Some(roots: 10,6,33,13,8,30,19
outgoing:
	0:
	1:
	2:
	3:
	4:
	5:
	6: (5,AM-TMP)
	7:
	8: (2,AM-LOC) (6,A0) (10,A1) (13,A1)
	9:
	10: (9,A1) (10,A1) (12,A1) (13,A1)
	11:
	12:
	13: (9,A1) (10,A1) (12,A1) (13,A1)
	14:
	15:
	16:
	17:
	18:
	19: (21,A0) (23,A0) (26,A0)
	20:
	21:
	22:
	23:
	24:
	25:
	26:
	27:
	28:
	29:
	30: (19,A0) (33,A1)
	31:
	32:
	33: (32,AM-TMP)
	34:
```

**Comment by BeckySharp** [comment]
@kwalcock  fix pushed to your branch
i ran with that cdr and it completed (STUPID SLOW) but it finished without an infinite loop

**Comment by MihaiSurdeanu** [comment]
@BeckySharp : you're talking about the self loops for predicates 10 and 13?

**Comment by BeckySharp** [comment]
yeah

**Comment by MihaiSurdeanu** [comment]
I can confirm this happens in processors. I will push a fix soon.

**Comment by kwalcock** [comment]
Thanks, @BeckySharp.  I will give it a try on the last 4 of the 44591 files.

**Comment by MihaiSurdeanu** [comment]
Fwiw, this is a bug in my generation of enhanced roles, so it should be fixed there. I am working on it.

**Comment by MihaiSurdeanu** [comment]
A fix for this has been pushed in the master branch of processors.

**Comment by MihaiSurdeanu** [comment]
@BeckySharp: thanks for catching this! This was a subtle but fun edge case.

**Comment by kwalcock** [comment]
Becky's fix worked for all four problematic files, but it sounds like I should swap out that fix for the one in processors.  I'll see if that works.

**Comment by BeckySharp** [comment]
great work all, thanks!

**Comment by kwalcock** [comment]
Mihai's fix seems to prevent the infinite recursion as well.  The resulting groundings are slightly different, but I assume that's a reasonable consequence and plan to submit those.  Thanks both for figuring this out so quickly, much faster than I could have done.
