### ISSUE TITLE
compilation issue on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by kingfish777** [clulab/eidos#941]
Greetings - I encountered difficulties compiling eidos using sbt on Ubuntu 20.04 LTS. 

This is what I see when I run sbt 

`smalec@Enkidu:~/Projects/eidos$ sbt webapp/run
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/smalec/Projects/eidos/project
[info] Loading settings from release.sbt,test.sbt,version.sbt,compile.sbt,build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to eidos (in build file:/home/smalec/Projects/eidos/)
[info] Compiling 28 Scala sources to /home/smalec/Projects/eidos/eidoscommon/target/scala-2.12/classes ...
[error] /home/smalec/Projects/eidos/eidoscommon/src/main/scala/org/clulab/wm/eidoscommon/utils/PropertiesBuilder.scala:19:16: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     properties.putAll(propertiesBuilder.get)
[error]                ^
[error] one error found
[error] (eidoscommon / Compile / compileIncremental) Compilation failed
[error] Total time: 11 s, completed Jan 26, 2021, 5:36:01 PM
[INFO] [01/26/2021 17:36:01.366] [Thread-3] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
`

Thanks!
Scott

**Comment by kingfish777** [comment]
I resolved this issue by using an older JDK (oracle version 8). Best, Scott

**Comment by kwalcock** [comment]
Thanks for figuring it out.  We do indeed usually build with Java 8 and weren't aware that the build is broken with other versions.  We'll try to get it to work with some more or at least document the limitation.

**Comment by kwalcock** [comment]
Reformatted...

```
smalec@Enkidu:~/Projects/eidos$ sbt webapp/run
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/smalec/Projects/eidos/project
[info] Loading settings from release.sbt,test.sbt,version.sbt,compile.sbt,build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to eidos (in build file:/home/smalec/Projects/eidos/)
[info] Compiling 28 Scala sources to /home/smalec/Projects/eidos/eidoscommon/target/scala-2.12/classes ...
[error] /home/smalec/Projects/eidos/eidoscommon/src/main/scala/org/clulab/wm/eidoscommon/utils/PropertiesBuilder.scala:19:16: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     properties.putAll(propertiesBuilder.get)
[error]                ^
[error] one error found
[error] (eidoscommon / Compile / compileIncremental) Compilation failed
[error] Total time: 11 s, completed Jan 26, 2021, 5:36:01 PM
[INFO] [01/26/2021 17:36:01.366] [Thread-3] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

**Comment by kwalcock** [comment]
Compilation is fixed in #944.  There may still be some problems with unit tests passing on Java 11.

**Comment by kwalcock** [comment]
One unit test is failing, so I would avoid using Java 11 until we figure out the reason for the changed behavior.

**Comment by kwalcock** [comment]
For the time being, a check on the Java version number has been added to build.sbt and a note about the version has been added to the readme file.  Since Java 11 compatibility is a more general clulab issue that doesn't affect just eidos, I'm going to close this issue here and work on it elsewhere.  Thanks.
