### ISSUE TITLE
jalksdjkal

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#984]
adsjlaksj
daklsdj

- 
https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/EidosSystem.scala#L39

**Comment by BeckySharp** [comment]
dnam,sdn,

**Comment by BeckySharp** [comment]
> dnam,sdn,

dasdsd

**Comment by kwalcock** [comment]
Stroke?  Cat on the keyboard?

**Comment by BeckySharp** [comment]
> Stroke? Cat on the keyboard?

:) teaching an undergrad how to use github issues, i shoulda chosen a diff repo prob :)

**Comment by kwalcock** [comment]
👍
