### ISSUE TITLE
Error when regrounding via web app

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#987]
I updated my local Eidos repo to the latest master and then ran `sbt webapp/run` to start the webapp. When sending the regular request to do re-grounding (no changes to the code on our end since the last time this worked), I get the following error:
```
java.io.FileNotFoundException: /org/clulab/wm/eidos/english/ontologies/CompositionalOntology_v2.1_metadata.yml (The system cannot find the path specified)
```
Do I need to manually add this file to the path above inside the `eidos/target/scala-2.12/` folder? Or should I change the path specified in `eidos.conf` instead (which I haven't touched)?

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please look at this? Thank you!

**Comment by kwalcock** [comment]
It's supposed to be automatic.  I will give it a try in the morning.

**Comment by kwalcock** [comment]
I'm not seeing the same results here.  Just to be sure that the configuration was clean, I renamed ~/.ivy2 to something else and also did `sbt clean`.  When everything was rebuilt, the webapp would run and work without complaint.  I also did the webapp/test which includes a request to reground and that ran as expected.  There was recently a problem with that ontology having an extra blank line that confused the parser, but both the ontology and eidos was patched for that.  You might check that you have those changes. 
 You might try rebuilding that `~/.ivy2` directory or at least checking that `~/.ivy2/cache/com.github.WorldModelers/Ontologies/jars/Ontologies-master-SNAPSHOT.jar` contains the AWOL `org/clulab/wm/eidos/english/ontologies/CompositionalOntology_v2.1_metadata.yml`.

**Comment by bgyori** [comment]
Thanks, I actually didn't know that `sbt clean` would be relevant in this situation but after I did that, the next compile+run started working.

**Comment by bgyori** [comment]
Turns out, I was wrong about the above - I forgot that I commented out the compositional ontology in `eidos.conf` before reporting back that things started working. If I enable it, it fails again, unfortunately, despite `sbt clean`... I'm trying again by deleting `~/.ivy2`.

**Comment by kwalcock** [comment]
Good luck.

**Comment by kwalcock** [comment]
I am moving that Eidos server from running on the OS to running on Docker.  The machine may be rebooted soon and I'd like Eidos to start automatically.  I'll watch for your problem.

**Comment by bgyori** [comment]
Okay, deleting `~/.ivy2` seems to have solved the issue, I must have had something cached in there from a long time ago that caused problems.

**Comment by kwalcock** [comment]
FWIW I'm not having much luck running Eidos in Docker.  The `sbt update` command seems to hang.  `sbt.version` was recently incremented.  Perhaps there's a problem with it.
